--[[
~> HORSE⇿@SOURCE_HORSE 
]] 
function zhrfa(msg)
text = nil
if msg and msg.content and msg.content.text then
text = msg.content.text.text
end
msg_chat_id = msg.chat_id
msg_id = msg.id
if tonumber(msg.sender_id.user_id) == tonumber(Fast) then
return false
end
if text then
local neww = Redis:get(Fast.."Get:Reides:Commands:Group"..msg.chat_id..":"..text)
if neww then
text = neww or text
end
end
if text == "زخرفه" then
local reply_markup = bot.replyMarkup{
type = 'inline',
data = {
{
{text = '✔️ زخـرفه انلاين', data = msg.sender_id.user_id..'/Zhrfinlin'},{text = 'زخـرفه ➕', data = msg.sender_id.user_id..'/ZhrAde'},
},
}
}
return bot.sendText(msg_chat_id, msg_id, '• اختر نوع الزخرفه \n✔️ › زخـرفه انلاين\n ➕ › زخـرفـه', 'md', false, false, false, false, reply_markup)
end

------------------------------

if Redis:get(Fast..":ZhrfNow:ar"..msg.sender_id.user_id) then
Redis:del(Fast..":ZhrfNow:ar"..msg.sender_id.user_id)
if string.len(text) > 300 then
return bot.sendText(msg_chat_id,msg_id,"•  لا يمكنك زخرفه اكثر من 20 حرف \n•  ارسل امر زخرفه وحاول مجددا بحروف اقل","md",true)      
elseif text:match("\n") then
return bot.sendText(msg_chat_id,msg_id,"•  لا يمكن زخرفه نص يحتوي على اكثر من سطر .","md",true)  
end
local Zh_Ar13 = text:gsub('ض', 'ضِٰــ' ) Zh_Ar13 = Zh_Ar13:gsub('ص', 'صِٰــ' ) Zh_Ar13 = Zh_Ar13:gsub('ث', 'ثِٰــ' ) Zh_Ar13 = Zh_Ar13:gsub('ق', 'قِٰــ' ) Zh_Ar13 = Zh_Ar13:gsub('ف', 'فِٰ͒ــ' ) Zh_Ar13 = Zh_Ar13:gsub('غ', 'غِٰــ' ) Zh_Ar13 = Zh_Ar13:gsub('ع', 'عِٰــ' ) Zh_Ar13 = Zh_Ar13:gsub('خ', 'خِٰ̐ــ' ) Zh_Ar13 = Zh_Ar13:gsub('ح', 'حِٰــ' ) Zh_Ar13 = Zh_Ar13:gsub('ج', 'جِٰــ' ) Zh_Ar13 = Zh_Ar13:gsub('ش', 'شِٰــ' ) Zh_Ar13 = Zh_Ar13:gsub('س', 'سِٰــ' ) Zh_Ar13 = Zh_Ar13:gsub('ي', 'يِٰــ' ) Zh_Ar13 = Zh_Ar13:gsub('ب', 'بِٰــ' ) Zh_Ar13 = Zh_Ar13:gsub('ل', 'لِٰــ' ) Zh_Ar13 = Zh_Ar13:gsub('ا', 'آ' ) Zh_Ar13 = Zh_Ar13:gsub('ت', 'تِٰــ' ) Zh_Ar13 = Zh_Ar13:gsub('ن', 'نِٰــ' ) Zh_Ar13 = Zh_Ar13:gsub('م', 'مِٰــ' ) Zh_Ar13 = Zh_Ar13:gsub('ك', 'ڪِٰــ' ) Zh_Ar13 = Zh_Ar13:gsub('ط', 'طِٰــ' ) Zh_Ar13 = Zh_Ar13:gsub('ظ', 'ظِٰــ' ) Zh_Ar13 = Zh_Ar13:gsub('ء', 'ء' ) Zh_Ar13 = Zh_Ar13:gsub('ؤ', 'ؤ' ) Zh_Ar13 = Zh_Ar13:gsub('ر', 'ر' ) Zh_Ar13 = Zh_Ar13:gsub('ى', 'ى' ) Zh_Ar13 = Zh_Ar13:gsub('ز', 'ز' ) Zh_Ar13 = Zh_Ar13:gsub('و', 'ﯛ̲୭' ) Zh_Ar13 = Zh_Ar13:gsub("ه", "໋۠هہؚ")
local Zh_Ar12 = text:gsub('ا','آ' ) Zh_Ar12 = Zh_Ar12:gsub("ب","بّہ" ) Zh_Ar12 = Zh_Ar12:gsub("ت","تَہَٰ" ) Zh_Ar12 = Zh_Ar12:gsub("ح","حہٰٰ" ) Zh_Ar12 = Zh_Ar12:gsub("ج","جْۧ" ) Zh_Ar12 = Zh_Ar12:gsub("خ","خٰ̐ہ" ) Zh_Ar12 = Zh_Ar12:gsub("د","د" ) Zh_Ar12 = Zh_Ar12:gsub("ذ","ذِ" ) Zh_Ar12 = Zh_Ar12:gsub("ر","ر" ) Zh_Ar12 = Zh_Ar12:gsub("ز","زَ" ) Zh_Ar12 = Zh_Ar12:gsub("س","سٰٰٓ" ) Zh_Ar12 = Zh_Ar12:gsub("ش","شِٰہٰٰ" ) Zh_Ar12 = Zh_Ar12:gsub("ص","صۛہٰٰ" ) Zh_Ar12 = Zh_Ar12:gsub("ض","ضۜہٰٰ" ) Zh_Ar12 = Zh_Ar12:gsub("ظ","ظۗہٰٰ" ) Zh_Ar12 = Zh_Ar12:gsub("غ","غہٰٰ" ) Zh_Ar12 = Zh_Ar12:gsub("ف","ف͒ہٰٰ" ) Zh_Ar12 = Zh_Ar12:gsub("ق","قྀ̲ہٰٰٰ" ) Zh_Ar12 = Zh_Ar12:gsub("ك","ڪٰྀہٰٰٖ" ) Zh_Ar12 = Zh_Ar12:gsub("ل","ل" ) Zh_Ar12 = Zh_Ar12:gsub("ن","نَِٰہٰ" ) Zh_Ar12 = Zh_Ar12:gsub("ه","ھہ" ) Zh_Ar12 = Zh_Ar12:gsub("و","وِ" ) Zh_Ar12 = Zh_Ar12:gsub("طۨہٰٰ","ط" ) Zh_Ar12 = Zh_Ar12:gsub("ث","ثہٰٰ" ) Zh_Ar12 = Zh_Ar12:gsub("ي","يِٰہ" ) Zh_Ar12 = Zh_Ar12:gsub("ع","؏ۤـہٰٰ")
local Zh_Ar11 = text:gsub('ض', 'ضُ͠' ) Zh_Ar11 = Zh_Ar11:gsub('ص', 'صّ͠' ) Zh_Ar11 = Zh_Ar11:gsub('ث', 'ثُ͠' ) Zh_Ar11 = Zh_Ar11:gsub('ق', 'ق͠' ) Zh_Ar11 = Zh_Ar11:gsub('ف', 'ف͠' ) Zh_Ar11 = Zh_Ar11:gsub('غ', 'غ͠' ) Zh_Ar11 = Zh_Ar11:gsub('ع', 'ع͠' ) Zh_Ar11 = Zh_Ar11:gsub('خ', 'ٌخ͠' ) Zh_Ar11 = Zh_Ar11:gsub('ح', 'حُ͠' ) Zh_Ar11 = Zh_Ar11:gsub('ج', 'جْ͠' ) Zh_Ar11 = Zh_Ar11:gsub('ش', 'شِ͠' ) Zh_Ar11 = Zh_Ar11:gsub('س', 'سِ͠' ) Zh_Ar11 = Zh_Ar11:gsub('ي', 'ي͠' ) Zh_Ar11 = Zh_Ar11:gsub('ب', 'بّ͠' ) Zh_Ar11 = Zh_Ar11:gsub('ل', 'ل͠' ) Zh_Ar11 = Zh_Ar11:gsub('ا', 'ا' ) Zh_Ar11 = Zh_Ar11:gsub('ت', 'تْ͠' ) Zh_Ar11 = Zh_Ar11:gsub('ن', 'ن͠' ) Zh_Ar11 = Zh_Ar11:gsub('م', 'م͠' ) Zh_Ar11 = Zh_Ar11:gsub('ك', 'گ͠' ) Zh_Ar11 = Zh_Ar11:gsub('طِ', 'ط͠' ) Zh_Ar11 = Zh_Ar11:gsub('ظ', 'ظٌ͠' ) Zh_Ar11 = Zh_Ar11:gsub('ء', '͠ء' ) Zh_Ar11 = Zh_Ar11:gsub('وَ', 'و͠' ) Zh_Ar11 = Zh_Ar11:gsub('ر', 'ر͠' ) Zh_Ar11 = Zh_Ar11:gsub('ى', '͠ى' ) Zh_Ar11 = Zh_Ar11:gsub('ز', 'ز͠' ) Zh_Ar11 = Zh_Ar11:gsub('ض','ض͠' ) Zh_Ar11 = Zh_Ar11:gsub('و', 'وَ͠' ) Zh_Ar11 = Zh_Ar11:gsub("ه", "ه͠")
local Zh_Ar10 = text:gsub('ض', 'ضِـٰٚـ' ) Zh_Ar10 = Zh_Ar10:gsub('ص', 'صِـٰٚـ' ) Zh_Ar10 = Zh_Ar10:gsub('ث', 'ثِـٰٚـ' ) Zh_Ar10 = Zh_Ar10:gsub('ق', 'قِـٰٚـ' ) Zh_Ar10 = Zh_Ar10:gsub('ف', 'فِ͒ـٰٚـ' ) Zh_Ar10 = Zh_Ar10:gsub('غ', 'غِـٰٚـ' ) Zh_Ar10 = Zh_Ar10:gsub('ع', 'عِـٰٚـ' ) Zh_Ar10 = Zh_Ar10:gsub('خ', 'خِ̐ـٰٚـ' ) Zh_Ar10 = Zh_Ar10:gsub('ح', 'حِـٰٚـ' ) Zh_Ar10 = Zh_Ar10:gsub('ج', 'جِـٰٚـِِـٰٚـِْ' ) Zh_Ar10 = Zh_Ar10:gsub('ش', 'شِـٰٚـ' ) Zh_Ar10 = Zh_Ar10:gsub('س', 'سِـٰٚـ' ) Zh_Ar10 = Zh_Ar10:gsub('ي', 'يِـٰٚـ' ) Zh_Ar10 = Zh_Ar10:gsub('ب', 'بِـٰٚـ' ) Zh_Ar10 = Zh_Ar10:gsub('ل', 'لِـٰٚـ' ) Zh_Ar10 = Zh_Ar10:gsub('ا', 'آ' ) Zh_Ar10 = Zh_Ar10:gsub('ت', 'تِـٰٚـ' ) Zh_Ar10 = Zh_Ar10:gsub('ن', 'نِـٰٚـ' ) Zh_Ar10 = Zh_Ar10:gsub('م', 'مِـٰٚـ' ) Zh_Ar10 = Zh_Ar10:gsub('ك', 'ڪِـٰٚـ' ) Zh_Ar10 = Zh_Ar10:gsub('ط', 'طِـٰٚـ' ) Zh_Ar10 = Zh_Ar10:gsub('ذ', 'ذِـٰٚـ' ) Zh_Ar10 = Zh_Ar10:gsub('ظ', 'ظِـٰٚـ' ) Zh_Ar10 = Zh_Ar10:gsub('ء', 'ء' ) Zh_Ar10 = Zh_Ar10:gsub('ؤ', 'ؤ' ) Zh_Ar10 = Zh_Ar10:gsub('ر', 'ر' ) Zh_Ar10 = Zh_Ar10:gsub('ى', 'ى' ) Zh_Ar10 = Zh_Ar10:gsub('ز', 'ز' ) Zh_Ar10 = Zh_Ar10:gsub('ظ', 'ظِـٰٚـ' ) Zh_Ar10 = Zh_Ar10:gsub('و', 'ﯛ̲୭' ) Zh_Ar10 = Zh_Ar10:gsub("ه", "ۿۿہ")
local Zh_Ar9  = text:gsub('ض', 'ض' ) Zh_Ar9 = Zh_Ar9:gsub('ص', 'صہٰ' ) Zh_Ar9 = Zh_Ar9:gsub('ث', 'ثہٰـ' ) Zh_Ar9 = Zh_Ar9:gsub('ق', 'قہٰ' ) Zh_Ar9 = Zh_Ar9:gsub('ف', 'فہٰ' ) Zh_Ar9 = Zh_Ar9:gsub('غ', 'غـْ' ) Zh_Ar9 = Zh_Ar9:gsub('ع', 'ع' ) Zh_Ar9 = Zh_Ar9:gsub('ه', 'هٰہٰٖ' ) Zh_Ar9 = Zh_Ar9:gsub('خ', 'خخَـ' ) Zh_Ar9 = Zh_Ar9:gsub('ح', 'حہٰ' ) Zh_Ar9 = Zh_Ar9:gsub('ج', 'ججہٰ' ) Zh_Ar9 = Zh_Ar9:gsub('د', 'دَ' ) Zh_Ar9 = Zh_Ar9:gsub('ذ', 'ذّ' ) Zh_Ar9 = Zh_Ar9:gsub('ش', 'ششہٰ' ) Zh_Ar9 = Zh_Ar9:gsub('س', 'سہٰ' ) Zh_Ar9 = Zh_Ar9:gsub('ي', 'يٰ' ) Zh_Ar9 = Zh_Ar9:gsub('ب', 'بٰٰ' ) Zh_Ar9 = Zh_Ar9:gsub('ل', 'لہٰ' ) Zh_Ar9 = Zh_Ar9:gsub('ا', 'آ' ) Zh_Ar9 = Zh_Ar9:gsub('ت', 'تہٰ' ) Zh_Ar9 = Zh_Ar9:gsub('ن', 'نہٰ' ) Zh_Ar9 = Zh_Ar9:gsub('م', 'مہٰ' ) Zh_Ar9 = Zh_Ar9:gsub('ك', 'ككہٰ' ) Zh_Ar9 = Zh_Ar9:gsub('ط', 'طہٰ' ) Zh_Ar9 = Zh_Ar9:gsub('ئ', ' ْئٰ' ) Zh_Ar9 = Zh_Ar9:gsub('ء', 'ء' ) Zh_Ar9 = Zh_Ar9:gsub('ؤ', 'ؤؤَ' ) Zh_Ar9 = Zh_Ar9:gsub('ر', 'رَ' ) Zh_Ar9 = Zh_Ar9:gsub('لا', 'لہٰا' ) Zh_Ar9 = Zh_Ar9:gsub('ى', 'ىہٰ' ) Zh_Ar9 = Zh_Ar9:gsub('ة', 'ة' ) Zh_Ar9 = Zh_Ar9:gsub('و', 'ہٰو' ) Zh_Ar9 = Zh_Ar9:gsub('ز', 'ز' ) Zh_Ar9 = Zh_Ar9:gsub('ظ', 'ظہٰ')
local Zh_Ar8  = text:gsub('ض', 'ضہ' ) Zh_Ar8 = Zh_Ar8:gsub('ص', 'صہ' ) Zh_Ar8 = Zh_Ar8:gsub('ث', 'ثہ' ) Zh_Ar8 = Zh_Ar8:gsub('ق', 'قہ' ) Zh_Ar8 = Zh_Ar8:gsub('ف', 'فہ' ) Zh_Ar8 = Zh_Ar8:gsub('غ', 'غہ' ) Zh_Ar8 = Zh_Ar8:gsub('ع', 'عہ' ) Zh_Ar8 = Zh_Ar8:gsub('خ', 'خہ' ) Zh_Ar8 = Zh_Ar8:gsub('ح', 'حہ' ) Zh_Ar8 = Zh_Ar8:gsub('ج', 'جہ' ) Zh_Ar8 = Zh_Ar8:gsub('ش', 'شہ' ) Zh_Ar8 = Zh_Ar8:gsub('س', 'سہ' ) Zh_Ar8 = Zh_Ar8:gsub('ي', 'يہ' ) Zh_Ar8 = Zh_Ar8:gsub('ب', 'بہ' ) Zh_Ar8 = Zh_Ar8:gsub('ل', 'ل' ) Zh_Ar8 = Zh_Ar8:gsub('ا', 'آ' ) Zh_Ar8 = Zh_Ar8:gsub('ت', 'تہ' ) Zh_Ar8 = Zh_Ar8:gsub('ن', 'نہ' ) Zh_Ar8 = Zh_Ar8:gsub('م', 'مہ' ) Zh_Ar8 = Zh_Ar8:gsub('ك', 'كہ' ) Zh_Ar8 = Zh_Ar8:gsub('ط', 'طہ' ) Zh_Ar8 = Zh_Ar8:gsub('ظ', 'ظہ' ) Zh_Ar8 = Zh_Ar8:gsub('ء', 'ء' ) Zh_Ar8 = Zh_Ar8:gsub('ؤ', 'ؤ' ) Zh_Ar8 = Zh_Ar8:gsub('ر', 'ر' ) Zh_Ar8 = Zh_Ar8:gsub('ى', 'ى' ) Zh_Ar8 = Zh_Ar8:gsub('ز', 'ز' ) Zh_Ar8 = Zh_Ar8:gsub('و', 'ﯛ̲୭' ) Zh_Ar8 = Zh_Ar8:gsub("ه", "ۿۿہ")
local Zh_Ar7  = text:gsub('ض', 'ﺿ̭͠' ) Zh_Ar7 = Zh_Ar7:gsub('ص', 'ﺻ͡' ) Zh_Ar7 = Zh_Ar7:gsub('ث', 'ﺜ̲' ) Zh_Ar7 = Zh_Ar7:gsub('ق', 'ﭰ' ) Zh_Ar7 = Zh_Ar7:gsub('ف', 'ﻓ̲' ) Zh_Ar7 = Zh_Ar7:gsub('غ', 'ﻏ̲' ) Zh_Ar7 = Zh_Ar7:gsub('ع', 'ﻌ̲' ) Zh_Ar7 = Zh_Ar7:gsub('ه', 'ﮬ̲̌' ) Zh_Ar7 = Zh_Ar7:gsub('خ', 'خٌ' ) Zh_Ar7 = Zh_Ar7:gsub('ح', 'ﺣ̅' ) Zh_Ar7 = Zh_Ar7:gsub('ج', 'جُ' ) Zh_Ar7 = Zh_Ar7:gsub('د', 'ډ̝' ) Zh_Ar7 = Zh_Ar7:gsub('ذ', 'ذً' ) Zh_Ar7 = Zh_Ar7:gsub('ش', 'ﺷ̲' ) Zh_Ar7 = Zh_Ar7:gsub('س', 'ﺳ̉' ) Zh_Ar7 = Zh_Ar7:gsub('ي', 'ﯾ̃̐' ) Zh_Ar7 = Zh_Ar7:gsub('ب', 'ﺑ̲' ) Zh_Ar7 = Zh_Ar7:gsub('ل', 'ا̄ﻟ' ) Zh_Ar7 = Zh_Ar7:gsub('ا', 'ﺈ̃' ) Zh_Ar7 = Zh_Ar7:gsub('ت', 'ټُ' ) Zh_Ar7 = Zh_Ar7:gsub('ن', 'ﻧ̲' ) Zh_Ar7 = Zh_Ar7:gsub('م', 'ﻣ̲̉' ) Zh_Ar7 = Zh_Ar7:gsub('ك', 'گ' ) Zh_Ar7 = Zh_Ar7:gsub('ط', 'ﻁ̲' ) Zh_Ar7 = Zh_Ar7:gsub('ئ', ' ْٰئ' ) Zh_Ar7 = Zh_Ar7:gsub('ء', 'ء' ) Zh_Ar7 = Zh_Ar7:gsub('ؤ', 'ؤ' ) Zh_Ar7 = Zh_Ar7:gsub('ر', 'ہڕ' ) Zh_Ar7 = Zh_Ar7:gsub('لا', 'ﻟ̲ﺂ̲' ) Zh_Ar7 = Zh_Ar7:gsub('ى', 'ى' ) Zh_Ar7 = Zh_Ar7:gsub('ة', 'ة' ) Zh_Ar7 = Zh_Ar7:gsub('و', 'ۇۈۉ' ) Zh_Ar7 = Zh_Ar7:gsub('ز', 'زُ' ) Zh_Ar7 = Zh_Ar7:gsub('ظ', 'ﻇ̲')
local Zh_Ar6  = text:gsub('ض', 'ض͜ـ' ) Zh_Ar6 = Zh_Ar6:gsub('ص', 'ص͜ـ' ) Zh_Ar6 = Zh_Ar6:gsub('ث', 'ث͜ـ͜ـ' ) Zh_Ar6 = Zh_Ar6:gsub('ق', 'ق͜ـ' ) Zh_Ar6 = Zh_Ar6:gsub('ف', 'ف͒͜ـ' ) Zh_Ar6 = Zh_Ar6:gsub('غ', 'غ͜ـ' ) Zh_Ar6 = Zh_Ar6:gsub('ع', 'ع͜ـ' ) Zh_Ar6 = Zh_Ar6:gsub('خ', 'خ̐͜ـ' ) Zh_Ar6 = Zh_Ar6:gsub('ح', 'ح͜ـ' ) Zh_Ar6 = Zh_Ar6:gsub('ج', 'ج͜ـ' ) Zh_Ar6 = Zh_Ar6:gsub('ش', 'ش͜ـ' ) Zh_Ar6 = Zh_Ar6:gsub('س', 'س͜ـ' ) Zh_Ar6 = Zh_Ar6:gsub('ي', 'ي͜ـ' ) Zh_Ar6 = Zh_Ar6:gsub('ب', 'ب͜ـ' ) Zh_Ar6 = Zh_Ar6:gsub('ل', 'ل͜ـ' ) Zh_Ar6 = Zh_Ar6:gsub('ا', 'آ' ) Zh_Ar6 = Zh_Ar6:gsub('ت', 'ت͜ـ' ) Zh_Ar6 = Zh_Ar6:gsub('ن', 'ن͜ـ' ) Zh_Ar6 = Zh_Ar6:gsub('م', 'م͜ـ' ) Zh_Ar6 = Zh_Ar6:gsub('ك', 'ڪ͜ـ' ) Zh_Ar6 = Zh_Ar6:gsub('ط', 'ط͜ـ' ) Zh_Ar6 = Zh_Ar6:gsub('ظ', 'ظ͜ـ' ) Zh_Ar6 = Zh_Ar6:gsub('ء', 'ء' ) Zh_Ar6 = Zh_Ar6:gsub('ؤ', 'ؤ' ) Zh_Ar6 = Zh_Ar6:gsub('ر', 'ر' ) Zh_Ar6 = Zh_Ar6:gsub('ى', 'ى' ) Zh_Ar6 = Zh_Ar6:gsub('ز', 'ز' ) Zh_Ar6 = Zh_Ar6:gsub('ظ', 'ظـ' ) Zh_Ar6 = Zh_Ar6:gsub('و', 'ﯛ̲୭' ) Zh_Ar6 = Zh_Ar6:gsub("ه", "ۿۿہ")
local Zh_Ar5  = text:gsub('ض', 'ضۜہٰٰ' ) Zh_Ar5 = Zh_Ar5:gsub('ص', 'ضۜہٰٰ' ) Zh_Ar5 = Zh_Ar5:gsub('ث', 'ثہٰٰ' ) Zh_Ar5 = Zh_Ar5:gsub('ق', 'قྀ̲ہٰٰ' ) Zh_Ar5 = Zh_Ar5:gsub('ف', 'ف͒ہٰٰ' ) Zh_Ar5 = Zh_Ar5:gsub('غ', 'غہٰٰ' ) Zh_Ar5 = Zh_Ar5:gsub('ع', 'عہٰٰ' ) Zh_Ar5 = Zh_Ar5:gsub('ه', 'هٰہٰٖ' ) Zh_Ar5 = Zh_Ar5:gsub('خ', 'خٰ̐ہ ' ) Zh_Ar5 = Zh_Ar5:gsub('ح', 'حہٰٰ' ) Zh_Ar5 = Zh_Ar5:gsub('ج', 'جـٰ̲ـہْۧ' ) Zh_Ar5 = Zh_Ar5:gsub('د', 'دٰ' ) Zh_Ar5 = Zh_Ar5:gsub('ذ', 'ذِٰ' ) Zh_Ar5 = Zh_Ar5:gsub('ش', 'شِٰہٰٰ' ) Zh_Ar5 = Zh_Ar5:gsub('س', 'سٰٓ' ) Zh_Ar5 = Zh_Ar5:gsub('ي', 'يِٰہ' ) Zh_Ar5 = Zh_Ar5:gsub('ب', 'بّہ' ) Zh_Ar5 = Zh_Ar5:gsub('ل', 'لـٰ̲ـہ' ) Zh_Ar5 = Zh_Ar5:gsub('ا', 'آ' ) Zh_Ar5 = Zh_Ar5:gsub('ت', 'تَہَٰ' ) Zh_Ar5 = Zh_Ar5:gsub('ن', 'نَِہ' ) Zh_Ar5 = Zh_Ar5:gsub('م', 'مٰ̲ہ' ) Zh_Ar5 = Zh_Ar5:gsub('ك', 'ڪٰྀہٰٰ' ) Zh_Ar5 = Zh_Ar5:gsub('ط', 'طۨہٰٰ' ) Zh_Ar5 = Zh_Ar5:gsub('ئ', 'ئ ْٰ' ) Zh_Ar5 = Zh_Ar5:gsub('ء', 'ء' ) Zh_Ar5 = Zh_Ar5:gsub('ؤ', 'ؤ' ) Zh_Ar5 = Zh_Ar5:gsub('ر', 'رَ' ) Zh_Ar5 = Zh_Ar5:gsub('لا', 'لہا' ) Zh_Ar5 = Zh_Ar5:gsub('ى', 'ىْ' ) Zh_Ar5 = Zh_Ar5:gsub('ة', 'ة' ) Zh_Ar5 = Zh_Ar5:gsub('و', 'وِٰ' ) Zh_Ar5 = Zh_Ar5:gsub('ز', 'زَٰ' ) Zh_Ar5 = Zh_Ar5:gsub('ظ', 'ظۗہٰٰ')
local Zh_Ar4  = text:gsub('ض', 'ضـٰ̲ـہۜہٰٰ' ) Zh_Ar4 = Zh_Ar4:gsub('ص', 'صـٰ̲ـہۛہٰٰ' ) Zh_Ar4 = Zh_Ar4:gsub('ث', 'ثـٰ̲ـہہٰٰ' ) Zh_Ar4 = Zh_Ar4:gsub('ق', 'قـٰ̲ـہྀ̲ہٰٰ' ) Zh_Ar4 = Zh_Ar4:gsub('ف', 'فـٰ̲ـہ͒ہٰٰ' ) Zh_Ar4 = Zh_Ar4:gsub('غ', 'غـٰ̲ـہہٰٰ' ) Zh_Ar4 = Zh_Ar4:gsub('ع', 'غـٰ̲ـہہٰٰ' ) Zh_Ar4 = Zh_Ar4:gsub('ه', 'هٰہٰٖ' ) Zh_Ar4 = Zh_Ar4:gsub('خ', 'خـٰ̲ـہٰ̐ہ ' ) Zh_Ar4 = Zh_Ar4:gsub('ح', 'حـٰ̲ـہہٰٰ' ) Zh_Ar4 = Zh_Ar4:gsub('ج', 'جـٰ̲ـہْۧ' ) Zh_Ar4 = Zh_Ar4:gsub('د', 'دٰ' ) Zh_Ar4 = Zh_Ar4:gsub('ذ', 'ذِٰ' ) Zh_Ar4 = Zh_Ar4:gsub('ش', 'شـٰ̲ـہِٰہٰٰ' ) Zh_Ar4 = Zh_Ar4:gsub('س', 'شـٰ̲ـہِٰہٰٰ' ) Zh_Ar4 = Zh_Ar4:gsub('ي', 'شـٰ̲ـہِٰہٰٰ' ) Zh_Ar4 = Zh_Ar4:gsub('ب', 'بـٰ̲ـہّہ' ) Zh_Ar4 = Zh_Ar4:gsub('ل', 'لـٰ̲ـہ' ) Zh_Ar4 = Zh_Ar4:gsub('ا', 'آ' ) Zh_Ar4 = Zh_Ar4:gsub('ت', 'تـٰ̲ـہَہَٰ' ) Zh_Ar4 = Zh_Ar4:gsub('ن', 'نـٰ̲ـہَِہ' ) Zh_Ar4 = Zh_Ar4:gsub('م', 'مـٰ̲ـہٰ̲ہ' ) Zh_Ar4 = Zh_Ar4:gsub('ك', 'ڪٰྀہٰٰ' ) Zh_Ar4 = Zh_Ar4:gsub('ط', 'طـٰ̲ـہۨہٰٰ' ) Zh_Ar4 = Zh_Ar4:gsub('ئ', 'ئ ْٰ' ) Zh_Ar4 = Zh_Ar4:gsub('ء', 'ء' ) Zh_Ar4 = Zh_Ar4:gsub('ؤ', 'ؤ' ) Zh_Ar4 = Zh_Ar4:gsub('ر', 'رَ' ) Zh_Ar4 = Zh_Ar4:gsub('لا', 'لہا' ) Zh_Ar4 = Zh_Ar4:gsub('ى', 'ىْ' ) Zh_Ar4 = Zh_Ar4:gsub('ة', 'ة' ) Zh_Ar4 = Zh_Ar4:gsub('و', 'وِٰ' ) Zh_Ar4 = Zh_Ar4:gsub('ز', 'زَٰ' ) Zh_Ar4 = Zh_Ar4:gsub('ظ', 'ظۗہٰٰ')
local Zh_Ar3  = text:gsub('ض', 'ض' ) Zh_Ar3 = Zh_Ar3:gsub('ص', 'ص' ) Zh_Ar3 = Zh_Ar3:gsub('ث', 'ثہ' ) Zh_Ar3 = Zh_Ar3:gsub('ق', 'ق' ) Zh_Ar3 = Zh_Ar3:gsub('ف', 'فُہ' ) Zh_Ar3 = Zh_Ar3:gsub('غ', 'غہ' ) Zh_Ar3 = Zh_Ar3:gsub('ع', 'عہ' ) Zh_Ar3 = Zh_Ar3:gsub('ه', 'هٰہٰٖ' ) Zh_Ar3 = Zh_Ar3:gsub('خ', 'خہ' ) Zh_Ar3 = Zh_Ar3:gsub('ح', 'حہ' ) Zh_Ar3 = Zh_Ar3:gsub('ج', 'جہ' ) Zh_Ar3 = Zh_Ar3:gsub('د', 'د' ) Zh_Ar3 = Zh_Ar3:gsub('ذ', 'ذ' ) Zh_Ar3 = Zh_Ar3:gsub('ش', 'شہ' ) Zh_Ar3 = Zh_Ar3:gsub('س', 'سہ' ) Zh_Ar3 = Zh_Ar3:gsub('ي', 'يہ' ) Zh_Ar3 = Zh_Ar3:gsub('ب', 'بّ' ) Zh_Ar3 = Zh_Ar3:gsub('ل', 'لہ' ) Zh_Ar3 = Zh_Ar3:gsub('ا', 'ا' ) Zh_Ar3 = Zh_Ar3:gsub('ت', 'تہ' ) Zh_Ar3 = Zh_Ar3:gsub('ن', 'نٰہٰٖ' ) Zh_Ar3 = Zh_Ar3:gsub('م', 'مٰہٰٖ' ) Zh_Ar3 = Zh_Ar3:gsub('ك', 'كُہ' ) Zh_Ar3 = Zh_Ar3:gsub('ط', 'طہ' ) Zh_Ar3 = Zh_Ar3:gsub('ئ', 'ئ ْٰ' ) Zh_Ar3 = Zh_Ar3:gsub('ء', 'ء' ) Zh_Ar3 = Zh_Ar3:gsub('ؤ', 'ؤ' ) Zh_Ar3 = Zh_Ar3:gsub('ر', 'رَ' ) Zh_Ar3 = Zh_Ar3:gsub('لا', 'لہا' ) Zh_Ar3 = Zh_Ar3:gsub('ى', 'ىْ' ) Zh_Ar3 = Zh_Ar3:gsub('ة', 'ة' ) Zh_Ar3 = Zh_Ar3:gsub('و', 'و' ) Zh_Ar3 = Zh_Ar3:gsub('ز', 'ز' ) Zh_Ar3 = Zh_Ar3:gsub('ظ', 'ظۗہٰٰ')
local Zh_Ar2  = text:gsub('ض', 'ضَٰـُـٰٓ' ) Zh_Ar2 = Zh_Ar2:gsub('ص', 'صَٰـُـٰٓ' ) Zh_Ar2 = Zh_Ar2:gsub('ث', 'ثَٰـُـٰٓ' ) Zh_Ar2 = Zh_Ar2:gsub('ق', 'قَٰـُـٰٓ' ) Zh_Ar2 = Zh_Ar2:gsub('ف', 'فَٰ͒ـُـٰٓ' ) Zh_Ar2 = Zh_Ar2:gsub('غ', 'غَٰـُـٰٓ' ) Zh_Ar2 = Zh_Ar2:gsub('ع', 'عَٰـُـٰٓ' ) Zh_Ar2 = Zh_Ar2:gsub('خ', 'خَٰ̐ـُـٰٓ' ) Zh_Ar2 = Zh_Ar2:gsub('ح', 'حَٰـُـٰٓ' ) Zh_Ar2 = Zh_Ar2:gsub('ج', 'جَٰـُـٰٓ' ) Zh_Ar2 = Zh_Ar2:gsub('ش', 'شَٰـُـٰٓ' ) Zh_Ar2 = Zh_Ar2:gsub('س', 'سَٰـُـٰٓ' ) Zh_Ar2 = Zh_Ar2:gsub('ي', 'يَٰـُـٰٓ' ) Zh_Ar2 = Zh_Ar2:gsub('ب', 'بَٰـُـٰٓ' ) Zh_Ar2 = Zh_Ar2:gsub('ل', 'لَٰـُـٰٓ' ) Zh_Ar2 = Zh_Ar2:gsub('ا', 'آ' ) Zh_Ar2 = Zh_Ar2:gsub('ت', 'تَٰـُـٰٓ' ) Zh_Ar2 = Zh_Ar2:gsub('ن', 'نَٰـُـٰٓ' ) Zh_Ar2 = Zh_Ar2:gsub('م', 'مَٰـُـٰٓ' ) Zh_Ar2 = Zh_Ar2:gsub('ك', 'ڪَٰـُـٰٓ' ) Zh_Ar2 = Zh_Ar2:gsub('ط', 'طَٰـُـٰٓ' ) Zh_Ar2 = Zh_Ar2:gsub('ظ', 'ظَٰـُـٰٓ' ) Zh_Ar2 = Zh_Ar2:gsub('ء', 'ء' ) Zh_Ar2 = Zh_Ar2:gsub('ؤ', 'ؤ' ) Zh_Ar2 = Zh_Ar2:gsub('ر', 'ر' ) Zh_Ar2 = Zh_Ar2:gsub('ى', 'ى' ) Zh_Ar2 = Zh_Ar2:gsub('ز', 'ز' ) Zh_Ar2 = Zh_Ar2:gsub('و', 'ﯛ̲୭' ) Zh_Ar2 = Zh_Ar2:gsub("ه", "ۿۿہ")
local Zh_Ar1  = text:gsub('ض', 'ضِٰـِۢ' ) Zh_Ar1 = Zh_Ar1:gsub('ص', 'صِٰـِۢ' ) Zh_Ar1 = Zh_Ar1:gsub('ث', 'ثِٰـِۢ' ) Zh_Ar1 = Zh_Ar1:gsub('ق', 'قِٰـِۢ' ) Zh_Ar1 = Zh_Ar1:gsub('ف', 'فِٰ͒ـِۢ' ) Zh_Ar1 = Zh_Ar1:gsub('غ', 'غِٰـِۢ' ) Zh_Ar1 = Zh_Ar1:gsub('ع', 'عِٰـِۢ' ) Zh_Ar1 = Zh_Ar1:gsub('خ', 'خِٰ̐ـِۢ' ) Zh_Ar1 = Zh_Ar1:gsub('ح', 'حِٰـِۢ' ) Zh_Ar1 = Zh_Ar1:gsub('ج', 'جِٰـِۢ' ) Zh_Ar1 = Zh_Ar1:gsub('ش', 'شِٰـِۢ' ) Zh_Ar1 = Zh_Ar1:gsub('س', 'سِٰـِۢ' ) Zh_Ar1 = Zh_Ar1:gsub('ي', 'يِٰـِۢ' ) Zh_Ar1 = Zh_Ar1:gsub('ب', 'بِٰـِۢ' ) Zh_Ar1 = Zh_Ar1:gsub('ل', 'لِٰـِۢ' ) Zh_Ar1 = Zh_Ar1:gsub('ا', 'آ' ) Zh_Ar1 = Zh_Ar1:gsub('ت', 'تِٰـِۢ' ) Zh_Ar1 = Zh_Ar1:gsub('ن', 'نِٰـِۢ' ) Zh_Ar1 = Zh_Ar1:gsub('م', 'مِٰـِۢ' ) Zh_Ar1 = Zh_Ar1:gsub('ك', 'ڪِٰـِۢ' ) Zh_Ar1 = Zh_Ar1:gsub('ط', 'طِٰـِۢ' ) Zh_Ar1 = Zh_Ar1:gsub('ظ', 'ظِٰـِۢ' ) Zh_Ar1 = Zh_Ar1:gsub('ء', 'ء' ) Zh_Ar1 = Zh_Ar1:gsub('ؤ', 'ؤ' ) Zh_Ar1 = Zh_Ar1:gsub('ر', 'ر' ) Zh_Ar1 = Zh_Ar1:gsub('ى', 'ى' ) Zh_Ar1 = Zh_Ar1:gsub('ز', 'ز' ) Zh_Ar1 = Zh_Ar1:gsub('و', 'ﯛ̲୭' ) Zh_Ar1 = Zh_Ar1:gsub("ه", "ۿۿہ")
Text_Zhrfa = '1 -`'..Zh_Ar1..'`'..
'\n2 -`'..Zh_Ar2..'`'..
'\n3 -`'..Zh_Ar3..'`'..
'\n4 -`'..Zh_Ar4..'`'..
'\n5 -`'..Zh_Ar5..'`'..
'\n6 -`'..Zh_Ar6..'`'..
'\n7 -`'..Zh_Ar7..'`'..
'\n8 -`'..Zh_Ar8..'`'..
'\n9 -`'..Zh_Ar9..'`'..
'\n10 -`'..Zh_Ar10..'`'..
'\n11 -`'..Zh_Ar11..'`'..
'\n12 -`'..Zh_Ar12..'`'..
'\n13 -`'..Zh_Ar13..'`'
Text_Zhrfa = Text_Zhrfa.."\n•  اضغط ع الاسم ليتم النسخ \n✓"
return bot.sendText(msg_chat_id,msg_id,Text_Zhrfa,"md",true)  
end
if Redis:get(Fast..":Zhrfinlin:en"..msg.sender_id.user_id) then
Redis:del(Fast..":Zhrfinlin:en"..msg.sender_id.user_id)
Redis:set(Fast..msg_chat_id..msg.sender_id.user_id.."zkrf:text", text)
if string.len(text) > 300 then
return bot.sendText(msg_chat_id,msg_id,"•  لا يمكنك زخرفه اكثر من 20 حرف \n•  ارسل امر زخرفه وحاول مجددا بحروف اقل","md",true)  
elseif text:match("\n") then
return bot.sendText(msg_chat_id,msg_id,"•  لا يمكن زخرفه نص يحتوي على اكثر من سطر .","md",true)  
end
text = text:gsub('A','a') text = text:gsub('S','s') text = text:gsub('D','d') text = text:gsub('F','f') text = text:gsub('G','g') text = text:gsub('H','h') text = text:gsub('J','j') text = text:gsub('K','k') text = text:gsub('L','l') text = text:gsub('Q','q') text = text:gsub('W','w') text = text:gsub('E','e' ) text = text:gsub('R','r' ) text = text:gsub('T','t' ) text = text:gsub('Y','y' ) text = text:gsub('U','u' ) text = text:gsub('I','i' ) text = text:gsub('O','o' ) text = text:gsub('P','p' ) text = text:gsub('Z','z' ) text = text:gsub('X','x' ) text = text:gsub('C','c' ) text = text:gsub('V','v' ) text = text:gsub('B','b' ) text = text:gsub('N','n' ) text = text:gsub('M','m')
local Q_bna1 = text:gsub('a','ᥲ️' ) Q_bna1 = Q_bna1:gsub('b','Ⴆ' ) Q_bna1 = Q_bna1:gsub('c','ᥴ' ) Q_bna1 = Q_bna1:gsub('d','ძ' ) Q_bna1 = Q_bna1:gsub('e','ᥱ' ) Q_bna1 = Q_bna1:gsub('f','f' ) Q_bna1 = Q_bna1:gsub('g','ᧁ' ) Q_bna1 = Q_bna1:gsub('h','Ꮒ' ) Q_bna1 = Q_bna1:gsub('i','Ꭵ' ) Q_bna1 = Q_bna1:gsub('j','᧒' ) Q_bna1 = Q_bna1:gsub('k','𝚔' ) Q_bna1 = Q_bna1:gsub('l','ᗩ' ) Q_bna1 = Q_bna1:gsub('m',' ꧑' ) Q_bna1 = Q_bna1:gsub('n','ꪀ' ) Q_bna1 = Q_bna1:gsub('o','ρ' ) Q_bna1 = Q_bna1:gsub('p','ρ' ) Q_bna1 = Q_bna1:gsub('q','ǫ' ) Q_bna1 = Q_bna1:gsub('r','ℛ' ) Q_bna1 = Q_bna1:gsub('s','᥉' ) Q_bna1 = Q_bna1:gsub('t','ƚ' ) Q_bna1 = Q_bna1:gsub('u','ᥙ' ) Q_bna1 = Q_bna1:gsub('v','᥎' ) Q_bna1 = Q_bna1:gsub('w','ꪝ' ) Q_bna1 = Q_bna1:gsub('x','᥊' ) Q_bna1 = Q_bna1:gsub('y','ꪗ' ) Q_bna1 = Q_bna1:gsub('z','ᤁ')
local Q_bna2 = text:gsub('a','ᴀ' ) Q_bna2 = Q_bna2:gsub('b','ʙ' ) Q_bna2 = Q_bna2:gsub('c','ᴄ' ) Q_bna2 = Q_bna2:gsub('d','ᴅ' ) Q_bna2 = Q_bna2:gsub('e','ᴇ' ) Q_bna2 = Q_bna2:gsub('f','ғ' ) Q_bna2 = Q_bna2:gsub('g','ɢ' ) Q_bna2 = Q_bna2:gsub('h','ʜ' ) Q_bna2 = Q_bna2:gsub('i','ɪ' ) Q_bna2 = Q_bna2:gsub('j','ᴊ' ) Q_bna2 = Q_bna2:gsub('k','ᴋ' ) Q_bna2 = Q_bna2:gsub('l','ʟ' ) Q_bna2 = Q_bna2:gsub('m','ᴍ' ) Q_bna2 = Q_bna2:gsub('n','ɴ' ) Q_bna2 = Q_bna2:gsub('o','ᴏ' ) Q_bna2 = Q_bna2:gsub('p','ᴘ' ) Q_bna2 = Q_bna2:gsub('q','ǫ' ) Q_bna2 = Q_bna2:gsub('r','ʀ' ) Q_bna2 = Q_bna2:gsub('s','s' ) Q_bna2 = Q_bna2:gsub('t','ᴛ' ) Q_bna2 = Q_bna2:gsub('u','ᴜ' ) Q_bna2 = Q_bna2:gsub('v','ᴠ' ) Q_bna2 = Q_bna2:gsub('w','ᴡ' ) Q_bna2 = Q_bna2:gsub('x','x' ) Q_bna2 = Q_bna2:gsub('y','ʏ' ) Q_bna2 = Q_bna2:gsub('z','ᴢ')
local Q_bna3 = text:gsub('a','Ａ' ) Q_bna3 = Q_bna3:gsub('b','Ｂ' ) Q_bna3 = Q_bna3:gsub('c','Ｃ' ) Q_bna3 = Q_bna3:gsub('d','Ｄ' ) Q_bna3 = Q_bna3:gsub('e','Ｅ' ) Q_bna3 = Q_bna3:gsub('f','Ｆ' ) Q_bna3 = Q_bna3:gsub('g','Ｇ' ) Q_bna3 = Q_bna3:gsub('h','Ｈ' ) Q_bna3 = Q_bna3:gsub('i','Ｉ' ) Q_bna3 = Q_bna3:gsub('j','Ｊ' ) Q_bna3 = Q_bna3:gsub('k','Ｋ' ) Q_bna3 = Q_bna3:gsub('l','Ｌ' ) Q_bna3 = Q_bna3:gsub('m','Ｍ' ) Q_bna3 = Q_bna3:gsub('n','Ｎ' ) Q_bna3 = Q_bna3:gsub('o','Ｏ' ) Q_bna3 = Q_bna3:gsub('p','Ｐ' ) Q_bna3 = Q_bna3:gsub('q','Ｑ' ) Q_bna3 = Q_bna3:gsub('r','Ｒ' ) Q_bna3 = Q_bna3:gsub('s','Ｓ' ) Q_bna3 = Q_bna3:gsub('t','Ｔ' ) Q_bna3 = Q_bna3:gsub('u','Ｕ' ) Q_bna3 = Q_bna3:gsub('v','Ｖ' ) Q_bna3 = Q_bna3:gsub('w','Ｗ' ) Q_bna3 = Q_bna3:gsub('x','Ｘ' ) Q_bna3 = Q_bna3:gsub('y','Ｙ' ) Q_bna3 = Q_bna3:gsub('z','Ｚ')
local Q_bna4 = text:gsub('a','𝗔' ) Q_bna4 = Q_bna4:gsub('b','𝗕' ) Q_bna4 = Q_bna4:gsub('c','𝗖' ) Q_bna4 = Q_bna4:gsub('d','𝗗' ) Q_bna4 = Q_bna4:gsub('e','𝗘' ) Q_bna4 = Q_bna4:gsub('f','f' ) Q_bna4 = Q_bna4:gsub('g','𝗚' ) Q_bna4 = Q_bna4:gsub('h','𝗛' ) Q_bna4 = Q_bna4:gsub('i','𝗜' ) Q_bna4 = Q_bna4:gsub('j','𝗝' ) Q_bna4 = Q_bna4:gsub('k','𝗞' ) Q_bna4 = Q_bna4:gsub('l','𝗟' ) Q_bna4 = Q_bna4:gsub('m','𝗠' ) Q_bna4 = Q_bna4:gsub('n','𝗡' ) Q_bna4 = Q_bna4:gsub('o','𝗢' ) Q_bna4 = Q_bna4:gsub('p','𝗣' ) Q_bna4 = Q_bna4:gsub('q','𝗤' ) Q_bna4 = Q_bna4:gsub('r','𝗥' ) Q_bna4 = Q_bna4:gsub('s','𝗦' ) Q_bna4 = Q_bna4:gsub('t','𝗧' ) Q_bna4 = Q_bna4:gsub('u','𝗨' ) Q_bna4 = Q_bna4:gsub('v','𝗩' ) Q_bna4 = Q_bna4:gsub('w','𝗪' ) Q_bna4 = Q_bna4:gsub('x','𝗫' ) Q_bna4 = Q_bna4:gsub('y','𝗬' ) Q_bna4 = Q_bna4:gsub('z','𝗭')
local Q_bna5 = text:gsub('a','𝐀' ) Q_bna5 = Q_bna5:gsub('b','𝐁' ) Q_bna5 = Q_bna5:gsub('c','𝐂' ) Q_bna5 = Q_bna5:gsub('d','𝐃' ) Q_bna5 = Q_bna5:gsub('e','𝐄' ) Q_bna5 = Q_bna5:gsub('f','𝐅' ) Q_bna5 = Q_bna5:gsub('g','𝐆' ) Q_bna5 = Q_bna5:gsub('h','𝐇' ) Q_bna5 = Q_bna5:gsub('i','𝐈' ) Q_bna5 = Q_bna5:gsub('j','𝐉' ) Q_bna5 = Q_bna5:gsub('k','𝐊' ) Q_bna5 = Q_bna5:gsub('l','𝑳' ) Q_bna5 = Q_bna5:gsub('m','𝐌' ) Q_bna5 = Q_bna5:gsub('n','𝐍' ) Q_bna5 = Q_bna5:gsub('o','𝐎' ) Q_bna5 = Q_bna5:gsub('p','𝐏' ) Q_bna5 = Q_bna5:gsub('q','𝐐' ) Q_bna5 = Q_bna5:gsub('r','𝐑' ) Q_bna5 = Q_bna5:gsub('s','𝐒' ) Q_bna5 = Q_bna5:gsub('t','𝐓' ) Q_bna5 = Q_bna5:gsub('u','𝐔' ) Q_bna5 = Q_bna5:gsub('v','𝐕' ) Q_bna5 = Q_bna5:gsub('w','𝐖' ) Q_bna5 = Q_bna5:gsub('x','𝐗' ) Q_bna5 = Q_bna5:gsub('y','𝐘' ) Q_bna5 = Q_bna5:gsub('z','𝐙')
local Q_bna6 = text:gsub('a','𝐚' ) Q_bna6 = Q_bna6:gsub('b','𝐛' ) Q_bna6 = Q_bna6:gsub('c','𝐜' ) Q_bna6 = Q_bna6:gsub('d','𝐝' ) Q_bna6 = Q_bna6:gsub('e','𝐞' ) Q_bna6 = Q_bna6:gsub('f','𝐅' ) Q_bna6 = Q_bna6:gsub('g','𝐠' ) Q_bna6 = Q_bna6:gsub('h','𝐡' ) Q_bna6 = Q_bna6:gsub('i','𝐢' ) Q_bna6 = Q_bna6:gsub('j','𝐣' ) Q_bna6 = Q_bna6:gsub('k','𝐤' ) Q_bna6 = Q_bna6:gsub('l','𝐥' ) Q_bna6 = Q_bna6:gsub('m','𝐦' ) Q_bna6 = Q_bna6:gsub('n','𝐧' ) Q_bna6 = Q_bna6:gsub('o','𝐨' ) Q_bna6 = Q_bna6:gsub('p','𝐩' ) Q_bna6 = Q_bna6:gsub('q','𝐪' ) Q_bna6 = Q_bna6:gsub('r','𝐫' ) Q_bna6 = Q_bna6:gsub('s','𝐬' ) Q_bna6 = Q_bna6:gsub('t','𝐭' ) Q_bna6 = Q_bna6:gsub('u','𝐮' ) Q_bna6 = Q_bna6:gsub('v','𝐯' ) Q_bna6 = Q_bna6:gsub('w','𝐰' ) Q_bna6 = Q_bna6:gsub('x','𝐱' ) Q_bna6 = Q_bna6:gsub('y','𝐲' ) Q_bna6 = Q_bna6:gsub('z','𝐳')
local Q_bna7 = text:gsub('a','𝑎' ) Q_bna7 = Q_bna7:gsub('b','𝑏' ) Q_bna7 = Q_bna7:gsub('c','𝑐' ) Q_bna7 = Q_bna7:gsub('d','𝑑' ) Q_bna7 = Q_bna7:gsub('e','𝑒' ) Q_bna7 = Q_bna7:gsub('f','𝒇' ) Q_bna7 = Q_bna7:gsub('g','𝑔' ) Q_bna7 = Q_bna7:gsub('h','ℎ' ) Q_bna7 = Q_bna7:gsub('i','𝑖' ) Q_bna7 = Q_bna7:gsub('j','𝑗' ) Q_bna7 = Q_bna7:gsub('k','𝑘' ) Q_bna7 = Q_bna7:gsub('l','𝑙' ) Q_bna7 = Q_bna7:gsub('m','𝑚' ) Q_bna7 = Q_bna7:gsub('n','𝑛' ) Q_bna7 = Q_bna7:gsub('o','𝑜' ) Q_bna7 = Q_bna7:gsub('p','𝑝' ) Q_bna7 = Q_bna7:gsub('q','𝑞' ) Q_bna7 = Q_bna7:gsub('r','𝑟' ) Q_bna7 = Q_bna7:gsub('s','𝑠' ) Q_bna7 = Q_bna7:gsub('t','𝑡' ) Q_bna7 = Q_bna7:gsub('u','𝑢' ) Q_bna7 = Q_bna7:gsub('v','𝑣' ) Q_bna7 = Q_bna7:gsub('w','𝑤' ) Q_bna7 = Q_bna7:gsub('x','𝑥' ) Q_bna7 = Q_bna7:gsub('y','𝑦' ) Q_bna7 = Q_bna7:gsub('z','𝑧')
local Q_bna8 = text:gsub('a','ᗩ' ) Q_bna8 = Q_bna8:gsub('b','β' ) Q_bna8 = Q_bna8:gsub('c','Ｃ' ) Q_bna8 = Q_bna8:gsub('d','Ɗ' ) Q_bna8 = Q_bna8:gsub('e','Ｅ' ) Q_bna8 = Q_bna8:gsub('f','Բ' ) Q_bna8 = Q_bna8:gsub('g','Ｇ' ) Q_bna8 = Q_bna8:gsub('h','ⴼ' ) Q_bna8 = Q_bna8:gsub('i','Ｉ' ) Q_bna8 = Q_bna8:gsub('j','Ј' ) Q_bna8 = Q_bna8:gsub('k','₭' ) Q_bna8 = Q_bna8:gsub('l','Ł' ) Q_bna8 = Q_bna8:gsub('m','ᗰ' ) Q_bna8 = Q_bna8:gsub('n','Ŋ' ) Q_bna8 = Q_bna8:gsub('o','σ' ) Q_bna8 = Q_bna8:gsub('p','Ꝑ' ) Q_bna8 = Q_bna8:gsub('q','℺' ) Q_bna8 = Q_bna8:gsub('r','Ꮢ' ) Q_bna8 = Q_bna8:gsub('s','₷' ) Q_bna8 = Q_bna8:gsub('t','Ƭ' ) Q_bna8 = Q_bna8:gsub('u','ᵿ' ) Q_bna8 = Q_bna8:gsub('v','ѵ' ) Q_bna8 = Q_bna8:gsub('w','Ꮤ' ) Q_bna8 = Q_bna8:gsub('x','χ' ) Q_bna8 = Q_bna8:gsub('y','ɣ' ) Q_bna8 = Q_bna8:gsub('z','Ꙃ')
local Q_bna9 = text:gsub('a','𝒂' ) Q_bna9 = Q_bna9:gsub('b','𝒃' ) Q_bna9 = Q_bna9:gsub('c','𝒄' ) Q_bna9 = Q_bna9:gsub('d','𝒅' ) Q_bna9 = Q_bna9:gsub('e','𝒆' ) Q_bna9 = Q_bna9:gsub('f','𝒇' ) Q_bna9 = Q_bna9:gsub('g','𝒈' ) Q_bna9 = Q_bna9:gsub('h','𝒉' ) Q_bna9 = Q_bna9:gsub('i','𝒊' ) Q_bna9 = Q_bna9:gsub('j','𝒋' ) Q_bna9 = Q_bna9:gsub('k','𝒌' ) Q_bna9 = Q_bna9:gsub('l','𝒍' ) Q_bna9 = Q_bna9:gsub('m','𝒎' ) Q_bna9 = Q_bna9:gsub('n','𝒏' ) Q_bna9 = Q_bna9:gsub('o','𝒐' ) Q_bna9 = Q_bna9:gsub('p','𝒑' ) Q_bna9 = Q_bna9:gsub('q','𝒒' ) Q_bna9 = Q_bna9:gsub('r','𝒓' ) Q_bna9 = Q_bna9:gsub('s','𝒔' ) Q_bna9 = Q_bna9:gsub('t','𝒕' ) Q_bna9 = Q_bna9:gsub('u','𝒖' ) Q_bna9 = Q_bna9:gsub('v','𝒗' ) Q_bna9 = Q_bna9:gsub('w','𝒘' ) Q_bna9 = Q_bna9:gsub('x','𝒙' ) Q_bna9 = Q_bna9:gsub('y','𝒚' ) Q_bna9 = Q_bna9:gsub('z','𝒛')
local Q_bna10 = text:gsub('a','𝔸' ) Q_bna10 = Q_bna10:gsub('b','𝔹' ) Q_bna10 = Q_bna10:gsub('c','ℂ' ) Q_bna10 = Q_bna10:gsub('d','𝔻' ) Q_bna10 = Q_bna10:gsub('e','𝔼' ) Q_bna10 = Q_bna10:gsub('f','𝔽' ) Q_bna10 = Q_bna10:gsub('g','𝔾' ) Q_bna10 = Q_bna10:gsub('h','ℍ' ) Q_bna10 = Q_bna10:gsub('i','𝕀' ) Q_bna10 = Q_bna10:gsub('j','𝕁' ) Q_bna10 = Q_bna10:gsub('k','𝕂' ) Q_bna10 = Q_bna10:gsub('l','𝕃' ) Q_bna10 = Q_bna10:gsub('m','𝕄' ) Q_bna10 = Q_bna10:gsub('n','ℕ' ) Q_bna10 = Q_bna10:gsub('o','𝕆' ) Q_bna10 = Q_bna10:gsub('p','ℙ' ) Q_bna10 = Q_bna10:gsub('q','ℚ' ) Q_bna10 = Q_bna10:gsub('r','ℝ' ) Q_bna10 = Q_bna10:gsub('s','𝕊' ) Q_bna10 = Q_bna10:gsub('t','𝕋' ) Q_bna10 = Q_bna10:gsub('u','𝕌' ) Q_bna10 = Q_bna10:gsub('v','𝕍' ) Q_bna10 = Q_bna10:gsub('w','𝕎' ) Q_bna10 = Q_bna10:gsub('x','𝕏' ) Q_bna10 = Q_bna10:gsub('y','𝕐' ) Q_bna10 = Q_bna10:gsub('z','ℤ')
local Q_bna11 = text:gsub('a','𝕬 ' ) Q_bna11 = Q_bna11:gsub('b','𝕭' ) Q_bna11 = Q_bna11:gsub('c','𝕮' ) Q_bna11 = Q_bna11:gsub('d','𝕯' ) Q_bna11 = Q_bna11:gsub('e','𝕰' ) Q_bna11 = Q_bna11:gsub('f','f' ) Q_bna11 = Q_bna11:gsub('g','𝕲' ) Q_bna11 = Q_bna11:gsub('h','𝕳' ) Q_bna11 = Q_bna11:gsub('i','𝕴' ) Q_bna11 = Q_bna11:gsub('j','𝕵' ) Q_bna11 = Q_bna11:gsub('k','𝕶' ) Q_bna11 = Q_bna11:gsub('l','𝕷' ) Q_bna11 = Q_bna11:gsub('m','𝕸' ) Q_bna11 = Q_bna11:gsub('n','𝕹' ) Q_bna11 = Q_bna11:gsub('o','𝕺' ) Q_bna11 = Q_bna11:gsub('p','𝕻' ) Q_bna11 = Q_bna11:gsub('q','𝕼' ) Q_bna11 = Q_bna11:gsub('r','𝕽' ) Q_bna11 = Q_bna11:gsub('s','𝕾' ) Q_bna11 = Q_bna11:gsub('t','𝕿' ) Q_bna11 = Q_bna11:gsub('u','𝖀' ) Q_bna11 = Q_bna11:gsub('v','𝖁' ) Q_bna11 = Q_bna11:gsub('w','𝖂' ) Q_bna11 = Q_bna11:gsub('x','𝖃' ) Q_bna11 = Q_bna11:gsub('y','𝖄' ) Q_bna11 = Q_bna11:gsub('z','𝖅')
local Q_bna12 = text:gsub('a','𝐴' ) Q_bna12 = Q_bna12:gsub('b','b' ) Q_bna12 = Q_bna12:gsub('c','𝐶' ) Q_bna12 = Q_bna12:gsub('d','𝐷' ) Q_bna12 = Q_bna12:gsub('e','𝐸' ) Q_bna12 = Q_bna12:gsub('f','𝐹' ) Q_bna12 = Q_bna12:gsub('g','𝐺' ) Q_bna12 = Q_bna12:gsub('h','𝐻' ) Q_bna12 = Q_bna12:gsub('i','𝐼' ) Q_bna12 = Q_bna12:gsub('j','𝐽' ) Q_bna12 = Q_bna12:gsub('k','𝐾' ) Q_bna12 = Q_bna12:gsub('l','𝐿' ) Q_bna12 = Q_bna12:gsub('m','𝑀' ) Q_bna12 = Q_bna12:gsub('n','𝑁' ) Q_bna12 = Q_bna12:gsub('o','𝑂' ) Q_bna12 = Q_bna12:gsub('p','𝑃' ) Q_bna12 = Q_bna12:gsub('q','𝑄' ) Q_bna12 = Q_bna12:gsub('r','𝑅' ) Q_bna12 = Q_bna12:gsub('s','𝑆' ) Q_bna12 = Q_bna12:gsub('t','𝑇' ) Q_bna12 = Q_bna12:gsub('u','𝐔' ) Q_bna12 = Q_bna12:gsub('v','𝑉' ) Q_bna12 = Q_bna12:gsub('w','𝑊' ) Q_bna12 = Q_bna12:gsub('x','𝑋' ) Q_bna12 = Q_bna12:gsub('y','𝑌' ) Q_bna12 = Q_bna12:gsub('z','𝑍')
local Q_bna13 = text:gsub('a','𝓪 ' ) Q_bna13 = Q_bna13:gsub('b','𝓫' ) Q_bna13 = Q_bna13:gsub('c','𝓬' ) Q_bna13 = Q_bna13:gsub('d','𝓭' ) Q_bna13 = Q_bna13:gsub('e','𝓮' ) Q_bna13 = Q_bna13:gsub('f','𝓯' ) Q_bna13 = Q_bna13:gsub('g','𝓰' ) Q_bna13 = Q_bna13:gsub('h','𝓱' ) Q_bna13 = Q_bna13:gsub('i','𝓲' ) Q_bna13 = Q_bna13:gsub('j','𝓳' ) Q_bna13 = Q_bna13:gsub('k','𝓴' ) Q_bna13 = Q_bna13:gsub('l','𝓵' ) Q_bna13 = Q_bna13:gsub('m','𝓶' ) Q_bna13 = Q_bna13:gsub('n','𝓷' ) Q_bna13 = Q_bna13:gsub('o','𝓸' ) Q_bna13 = Q_bna13:gsub('p','𝓹' ) Q_bna13 = Q_bna13:gsub('q','𝓺' ) Q_bna13 = Q_bna13:gsub('r','𝓻' ) Q_bna13 = Q_bna13:gsub('s','𝓼' ) Q_bna13 = Q_bna13:gsub('t','𝓽' ) Q_bna13 = Q_bna13:gsub('u','??' ) Q_bna13 = Q_bna13:gsub('v','𝓾' ) Q_bna13 = Q_bna13:gsub('w','𝔀' ) Q_bna13 = Q_bna13:gsub('x','𝔁' ) Q_bna13 = Q_bna13:gsub('y','𝔂' ) Q_bna13 = Q_bna13:gsub('z','𝔃')
local Q_bna14 = text:gsub('a','𝙰' ) Q_bna14 = Q_bna14:gsub('b','𝙱' ) Q_bna14 = Q_bna14:gsub('c','𝙲' ) Q_bna14 = Q_bna14:gsub('d','𝙳' ) Q_bna14 = Q_bna14:gsub('e','𝙴' ) Q_bna14 = Q_bna14:gsub('f','𝙵' ) Q_bna14 = Q_bna14:gsub('g','𝙶' ) Q_bna14 = Q_bna14:gsub('h','𝙷' ) Q_bna14 = Q_bna14:gsub('i','𝙸' ) Q_bna14 = Q_bna14:gsub('j','𝙹' ) Q_bna14 = Q_bna14:gsub('k','𝙺' ) Q_bna14 = Q_bna14:gsub('l','𝙻' ) Q_bna14 = Q_bna14:gsub('m','𝙼' ) Q_bna14 = Q_bna14:gsub('n','𝙽' ) Q_bna14 = Q_bna14:gsub('o','𝙾' ) Q_bna14 = Q_bna14:gsub('p','𝙿' ) Q_bna14 = Q_bna14:gsub('q','𝚀' ) Q_bna14 = Q_bna14:gsub('r','𝚁' ) Q_bna14 = Q_bna14:gsub('s','𝚂' ) Q_bna14 = Q_bna14:gsub('t','𝚃' ) Q_bna14 = Q_bna14:gsub('u','𝙺' ) Q_bna14 = Q_bna14:gsub('v','𝚅' ) Q_bna14 = Q_bna14:gsub('w','𝚆' ) Q_bna14 = Q_bna14:gsub('x','𝚇' ) Q_bna14 = Q_bna14:gsub('y','𝚈' ) Q_bna14 = Q_bna14:gsub('z','𝚉')
local Q_bna15 = text:gsub('a','𝖆' ) Q_bna15 = Q_bna15:gsub('b','𝖇' ) Q_bna15 = Q_bna15:gsub('c','𝖈' ) Q_bna15 = Q_bna15:gsub('d','𝖉' ) Q_bna15 = Q_bna15:gsub('e','𝖊' ) Q_bna15 = Q_bna15:gsub('f','𝖋' ) Q_bna15 = Q_bna15:gsub('g','𝖌' ) Q_bna15 = Q_bna15:gsub('h','𝖍' ) Q_bna15 = Q_bna15:gsub('i','𝖎' ) Q_bna15 = Q_bna15:gsub('j','𝖏' ) Q_bna15 = Q_bna15:gsub('k','𝖐' ) Q_bna15 = Q_bna15:gsub('l','𝖑' ) Q_bna15 = Q_bna15:gsub('m','𝖒' ) Q_bna15 = Q_bna15:gsub('n','𝖓' ) Q_bna15 = Q_bna15:gsub('o','𝖔' ) Q_bna15 = Q_bna15:gsub('p','𝖕' ) Q_bna15 = Q_bna15:gsub('q','𝖖' ) Q_bna15 = Q_bna15:gsub('r','𝖗' ) Q_bna15 = Q_bna15:gsub('s','𝖘' ) Q_bna15 = Q_bna15:gsub('t','𝖙' ) Q_bna15 = Q_bna15:gsub('u','𝖚' ) Q_bna15 = Q_bna15:gsub('v','𝖛' ) Q_bna15 = Q_bna15:gsub('w','𝖜' ) Q_bna15 = Q_bna15:gsub('x','𝖝' ) Q_bna15 = Q_bna15:gsub('y','𝖞' ) Q_bna15 = Q_bna15:gsub('z','𝖟')
local Q_bna16 = text:gsub('a','🅰' ) Q_bna16 = Q_bna16:gsub('b','🅱' ) Q_bna16 = Q_bna16:gsub('c','🅲' ) Q_bna16 = Q_bna16:gsub('d','🅳' ) Q_bna16 = Q_bna16:gsub('e','🅴' ) Q_bna16 = Q_bna16:gsub('f','🅵' ) Q_bna16 = Q_bna16:gsub('g','🅶' ) Q_bna16 = Q_bna16:gsub('h','🅷' ) Q_bna16 = Q_bna16:gsub('i','🅸' ) Q_bna16 = Q_bna16:gsub('j','🅹' ) Q_bna16 = Q_bna16:gsub('k','🅺' ) Q_bna16 = Q_bna16:gsub('l','🅻' ) Q_bna16 = Q_bna16:gsub('m','🅼' ) Q_bna16 = Q_bna16:gsub('n','🅽' ) Q_bna16 = Q_bna16:gsub('o','🅾' ) Q_bna16 = Q_bna16:gsub('p','🅿' ) Q_bna16 = Q_bna16:gsub('q','🆀' ) Q_bna16 = Q_bna16:gsub('r','🆁' ) Q_bna16 = Q_bna16:gsub('s','🆂' ) Q_bna16 = Q_bna16:gsub('t','🆃' ) Q_bna16 = Q_bna16:gsub('u','🆄' ) Q_bna16 = Q_bna16:gsub('v','🆅' ) Q_bna16 = Q_bna16:gsub('w','🆆' ) Q_bna16 = Q_bna16:gsub('x','🆇' ) Q_bna16 = Q_bna16:gsub('y','🆈' ) Q_bna16 = Q_bna16:gsub('z','🆉')                
local Q_bna17 = text:gsub('a','🄰' ) Q_bna17 = Q_bna17:gsub('b','🄱' ) Q_bna17 = Q_bna17:gsub('c','🄲' ) Q_bna17 = Q_bna17:gsub('d','🄳' ) Q_bna17 = Q_bna17:gsub('e','🄴' ) Q_bna17 = Q_bna17:gsub('f','🄵' ) Q_bna17 = Q_bna17:gsub('g','🄶' ) Q_bna17 = Q_bna17:gsub('h','🄷' ) Q_bna17 = Q_bna17:gsub('i','🄸' ) Q_bna17 = Q_bna17:gsub('j','🄹' ) Q_bna17 = Q_bna17:gsub('k','🄺' ) Q_bna17 = Q_bna17:gsub('l','🄻' ) Q_bna17 = Q_bna17:gsub('m','🄼' ) Q_bna17 = Q_bna17:gsub('n','🄽' ) Q_bna17 = Q_bna17:gsub('o','🄾' ) Q_bna17 = Q_bna17:gsub('p','🄿' ) Q_bna17 = Q_bna17:gsub('q','🅀' ) Q_bna17 = Q_bna17:gsub('r','🅁' ) Q_bna17 = Q_bna17:gsub('s','🅂' ) Q_bna17 = Q_bna17:gsub('t','🅃' ) Q_bna17 = Q_bna17:gsub('u','🅄' ) Q_bna17 = Q_bna17:gsub('v','🅅' ) Q_bna17 = Q_bna17:gsub('w','🅆' ) Q_bna17 = Q_bna17:gsub('x','🅇' ) Q_bna17 = Q_bna17:gsub('y','🅈' ) Q_bna17 = Q_bna17:gsub('z','🅉')
local Q_bna18 = text:gsub('a','🅐' ) Q_bna18= Q_bna18:gsub('b','🅑' ) Q_bna18= Q_bna18:gsub('c','🅒' ) Q_bna18= Q_bna18:gsub('d','🅓') Q_bna18 = Q_bna18:gsub('e','🅔' ) Q_bna18= Q_bna18:gsub('f','🅕' ) Q_bna18= Q_bna18:gsub('g','🅖' ) Q_bna18= Q_bna18:gsub('h','🅗' ) Q_bna18= Q_bna18:gsub('i','🅘' ) Q_bna18= Q_bna18:gsub('j','🅙' ) Q_bna18= Q_bna18:gsub('k','🅚' ) Q_bna18= Q_bna18:gsub('l','🅛' ) Q_bna18= Q_bna18:gsub('m','🅜' ) Q_bna18= Q_bna18:gsub('n','🅝' ) Q_bna18= Q_bna18:gsub('o','🅞' ) Q_bna18= Q_bna18:gsub('p','🅟' ) Q_bna18= Q_bna18:gsub('q','🅠' ) Q_bna18= Q_bna18:gsub('r','🅡' ) Q_bna18= Q_bna18:gsub('s','🅢' ) Q_bna18= Q_bna18:gsub('t','🅣' ) Q_bna18= Q_bna18:gsub('u','🅤' ) Q_bna18= Q_bna18:gsub('v','🅥' ) Q_bna18= Q_bna18:gsub('w','🅦' ) Q_bna18= Q_bna18:gsub('x','🅧' ) Q_bna18= Q_bna18:gsub('y','🅨' ) Q_bna18= Q_bna18:gsub('z','🅩')
Text_Zhrfa ="\n•  اضغط ع الازر ليتم ارسال الزخرفه \n✓"
local reply_markup = bot.replyMarkup{
type = 'inline',
data = {
{
{text = Q_bna1, data = msg.sender_id.user_id..'/NQ_bna1'},
},
{
{text = Q_bna2, data = msg.sender_id.user_id..'/N2'},
},
{
{text = Q_bna3, data = msg.sender_id.user_id..'/N3'},
},
{
{text = Q_bna4, data = msg.sender_id.user_id..'/N4'},
},
{
{text = Q_bna5, data = msg.sender_id.user_id..'/N5'},
},
{
{text = Q_bna6, data = msg.sender_id.user_id..'/N6'},
},
{
{text = Q_bna7, data = msg.sender_id.user_id..'/N7'},
},
{
{text = Q_bna8, data = msg.sender_id.user_id..'/N8'},
},
{
{text = Q_bna9, data = msg.sender_id.user_id..'/N9'},
},
{
{text = Q_bna10, data = msg.sender_id.user_id..'/N10'},
},
{
{text = Q_bna11, data = msg.sender_id.user_id..'/N11'},
},
{
{text = Q_bna12, data = msg.sender_id.user_id..'/N12'},
},
{
{text = Q_bna13, data = msg.sender_id.user_id..'/N13'},
},
{
{text = Q_bna14, data = msg.sender_id.user_id..'/N14'},
},
{
{text = Q_bna15, data = msg.sender_id.user_id..'/N15'},
},
{
{text = Q_bna16, data = msg.sender_id.user_id..'/N16'},
},
{
{text = Q_bna17, data = msg.sender_id.user_id..'/N17'},
},
{
{text = Q_bna18, data = msg.sender_id.user_id..'/N18'},
},
}
}
return bot.sendText(msg_chat_id, msg_id,Text_Zhrfa, 'md', false, false, false, false, reply_markup)
end

if Redis:get(Fast..":ZhrfNow:en"..msg.sender_id.user_id) then
Redis:del(Fast..":ZhrfNow:en"..msg.sender_id.user_id)
if string.len(text) > 300 then
return bot.sendText(msg_chat_id,msg_id,"•  لا يمكنك زخرفه اكثر من 20 حرف \n•  ارسل امر زخرفه وحاول مجددا بحروف اقل","md",true)  
elseif text:match("\n") then
return bot.sendText(msg_chat_id,msg_id,"•  لا يمكن زخرفه نص يحتوي على اكثر من سطر .","md",true)  
end
text = text:gsub('A','a') text = text:gsub('S','s') text = text:gsub('D','d') text = text:gsub('F','f') text = text:gsub('G','g') text = text:gsub('H','h') text = text:gsub('J','j') text = text:gsub('K','k') text = text:gsub('L','l') text = text:gsub('Q','q') text = text:gsub('W','w') text = text:gsub('E','e' ) text = text:gsub('R','r' ) text = text:gsub('T','t' ) text = text:gsub('Y','y' ) text = text:gsub('U','u' ) text = text:gsub('I','i' ) text = text:gsub('O','o' ) text = text:gsub('P','p' ) text = text:gsub('Z','z' ) text = text:gsub('X','x' ) text = text:gsub('C','c' ) text = text:gsub('V','v' ) text = text:gsub('B','b' ) text = text:gsub('N','n' ) text = text:gsub('M','m')
local Q_bna1 = text:gsub('a','ᥲ️' ) Q_bna1 = Q_bna1:gsub('b','Ⴆ' ) Q_bna1 = Q_bna1:gsub('c','ᥴ' ) Q_bna1 = Q_bna1:gsub('d','ძ' ) Q_bna1 = Q_bna1:gsub('e','ᥱ' ) Q_bna1 = Q_bna1:gsub('f','f' ) Q_bna1 = Q_bna1:gsub('g','ᧁ' ) Q_bna1 = Q_bna1:gsub('h','Ꮒ' ) Q_bna1 = Q_bna1:gsub('i','Ꭵ' ) Q_bna1 = Q_bna1:gsub('j','᧒' ) Q_bna1 = Q_bna1:gsub('k','𝚔' ) Q_bna1 = Q_bna1:gsub('l','ᗩ' ) Q_bna1 = Q_bna1:gsub('m',' ꧑' ) Q_bna1 = Q_bna1:gsub('n','ꪀ' ) Q_bna1 = Q_bna1:gsub('o','ρ' ) Q_bna1 = Q_bna1:gsub('p','ρ' ) Q_bna1 = Q_bna1:gsub('q','ǫ' ) Q_bna1 = Q_bna1:gsub('r','ℛ' ) Q_bna1 = Q_bna1:gsub('s','᥉' ) Q_bna1 = Q_bna1:gsub('t','ƚ' ) Q_bna1 = Q_bna1:gsub('u','ᥙ' ) Q_bna1 = Q_bna1:gsub('v','᥎' ) Q_bna1 = Q_bna1:gsub('w','ꪝ' ) Q_bna1 = Q_bna1:gsub('x','᥊' ) Q_bna1 = Q_bna1:gsub('y','ꪗ' ) Q_bna1 = Q_bna1:gsub('z','ᤁ')
local Q_bna2 = text:gsub('a','ᴀ' ) Q_bna2 = Q_bna2:gsub('b','ʙ' ) Q_bna2 = Q_bna2:gsub('c','ᴄ' ) Q_bna2 = Q_bna2:gsub('d','ᴅ' ) Q_bna2 = Q_bna2:gsub('e','ᴇ' ) Q_bna2 = Q_bna2:gsub('f','ғ' ) Q_bna2 = Q_bna2:gsub('g','ɢ' ) Q_bna2 = Q_bna2:gsub('h','ʜ' ) Q_bna2 = Q_bna2:gsub('i','ɪ' ) Q_bna2 = Q_bna2:gsub('j','ᴊ' ) Q_bna2 = Q_bna2:gsub('k','ᴋ' ) Q_bna2 = Q_bna2:gsub('l','ʟ' ) Q_bna2 = Q_bna2:gsub('m','ᴍ' ) Q_bna2 = Q_bna2:gsub('n','ɴ' ) Q_bna2 = Q_bna2:gsub('o','ᴏ' ) Q_bna2 = Q_bna2:gsub('p','ᴘ' ) Q_bna2 = Q_bna2:gsub('q','ǫ' ) Q_bna2 = Q_bna2:gsub('r','ʀ' ) Q_bna2 = Q_bna2:gsub('s','s' ) Q_bna2 = Q_bna2:gsub('t','ᴛ' ) Q_bna2 = Q_bna2:gsub('u','ᴜ' ) Q_bna2 = Q_bna2:gsub('v','ᴠ' ) Q_bna2 = Q_bna2:gsub('w','ᴡ' ) Q_bna2 = Q_bna2:gsub('x','x' ) Q_bna2 = Q_bna2:gsub('y','ʏ' ) Q_bna2 = Q_bna2:gsub('z','ᴢ')
local Q_bna3 = text:gsub('a','Ａ' ) Q_bna3 = Q_bna3:gsub('b','Ｂ' ) Q_bna3 = Q_bna3:gsub('c','Ｃ' ) Q_bna3 = Q_bna3:gsub('d','Ｄ' ) Q_bna3 = Q_bna3:gsub('e','Ｅ' ) Q_bna3 = Q_bna3:gsub('f','Ｆ' ) Q_bna3 = Q_bna3:gsub('g','Ｇ' ) Q_bna3 = Q_bna3:gsub('h','Ｈ' ) Q_bna3 = Q_bna3:gsub('i','Ｉ' ) Q_bna3 = Q_bna3:gsub('j','Ｊ' ) Q_bna3 = Q_bna3:gsub('k','Ｋ' ) Q_bna3 = Q_bna3:gsub('l','Ｌ' ) Q_bna3 = Q_bna3:gsub('m','Ｍ' ) Q_bna3 = Q_bna3:gsub('n','Ｎ' ) Q_bna3 = Q_bna3:gsub('o','Ｏ' ) Q_bna3 = Q_bna3:gsub('p','Ｐ' ) Q_bna3 = Q_bna3:gsub('q','Ｑ' ) Q_bna3 = Q_bna3:gsub('r','Ｒ' ) Q_bna3 = Q_bna3:gsub('s','Ｓ' ) Q_bna3 = Q_bna3:gsub('t','Ｔ' ) Q_bna3 = Q_bna3:gsub('u','Ｕ' ) Q_bna3 = Q_bna3:gsub('v','Ｖ' ) Q_bna3 = Q_bna3:gsub('w','Ｗ' ) Q_bna3 = Q_bna3:gsub('x','Ｘ' ) Q_bna3 = Q_bna3:gsub('y','Ｙ' ) Q_bna3 = Q_bna3:gsub('z','Ｚ')
local Q_bna4 = text:gsub('a','𝗔' ) Q_bna4 = Q_bna4:gsub('b','𝗕' ) Q_bna4 = Q_bna4:gsub('c','𝗖' ) Q_bna4 = Q_bna4:gsub('d','𝗗' ) Q_bna4 = Q_bna4:gsub('e','𝗘' ) Q_bna4 = Q_bna4:gsub('f','f' ) Q_bna4 = Q_bna4:gsub('g','𝗚' ) Q_bna4 = Q_bna4:gsub('h','𝗛' ) Q_bna4 = Q_bna4:gsub('i','𝗜' ) Q_bna4 = Q_bna4:gsub('j','𝗝' ) Q_bna4 = Q_bna4:gsub('k','𝗞' ) Q_bna4 = Q_bna4:gsub('l','𝗟' ) Q_bna4 = Q_bna4:gsub('m','𝗠' ) Q_bna4 = Q_bna4:gsub('n','𝗡' ) Q_bna4 = Q_bna4:gsub('o','𝗢' ) Q_bna4 = Q_bna4:gsub('p','𝗣' ) Q_bna4 = Q_bna4:gsub('q','𝗤' ) Q_bna4 = Q_bna4:gsub('r','𝗥' ) Q_bna4 = Q_bna4:gsub('s','𝗦' ) Q_bna4 = Q_bna4:gsub('t','𝗧' ) Q_bna4 = Q_bna4:gsub('u','𝗨' ) Q_bna4 = Q_bna4:gsub('v','𝗩' ) Q_bna4 = Q_bna4:gsub('w','𝗪' ) Q_bna4 = Q_bna4:gsub('x','𝗫' ) Q_bna4 = Q_bna4:gsub('y','𝗬' ) Q_bna4 = Q_bna4:gsub('z','𝗭')
local Q_bna5 = text:gsub('a','𝐀' ) Q_bna5 = Q_bna5:gsub('b','𝐁' ) Q_bna5 = Q_bna5:gsub('c','𝐂' ) Q_bna5 = Q_bna5:gsub('d','𝐃' ) Q_bna5 = Q_bna5:gsub('e','𝐄' ) Q_bna5 = Q_bna5:gsub('f','𝐅' ) Q_bna5 = Q_bna5:gsub('g','𝐆' ) Q_bna5 = Q_bna5:gsub('h','𝐇' ) Q_bna5 = Q_bna5:gsub('i','𝐈' ) Q_bna5 = Q_bna5:gsub('j','𝐉' ) Q_bna5 = Q_bna5:gsub('k','𝐊' ) Q_bna5 = Q_bna5:gsub('l','𝑳' ) Q_bna5 = Q_bna5:gsub('m','𝐌' ) Q_bna5 = Q_bna5:gsub('n','𝐍' ) Q_bna5 = Q_bna5:gsub('o','𝐎' ) Q_bna5 = Q_bna5:gsub('p','𝐏' ) Q_bna5 = Q_bna5:gsub('q','𝐐' ) Q_bna5 = Q_bna5:gsub('r','𝐑' ) Q_bna5 = Q_bna5:gsub('s','𝐒' ) Q_bna5 = Q_bna5:gsub('t','𝐓' ) Q_bna5 = Q_bna5:gsub('u','𝐔' ) Q_bna5 = Q_bna5:gsub('v','𝐕' ) Q_bna5 = Q_bna5:gsub('w','𝐖' ) Q_bna5 = Q_bna5:gsub('x','𝐗' ) Q_bna5 = Q_bna5:gsub('y','𝐘' ) Q_bna5 = Q_bna5:gsub('z','𝐙')
local Q_bna6 = text:gsub('a','𝐚' ) Q_bna6 = Q_bna6:gsub('b','𝐛' ) Q_bna6 = Q_bna6:gsub('c','𝐜' ) Q_bna6 = Q_bna6:gsub('d','𝐝' ) Q_bna6 = Q_bna6:gsub('e','𝐞' ) Q_bna6 = Q_bna6:gsub('f','𝐅' ) Q_bna6 = Q_bna6:gsub('g','𝐠' ) Q_bna6 = Q_bna6:gsub('h','𝐡' ) Q_bna6 = Q_bna6:gsub('i','𝐢' ) Q_bna6 = Q_bna6:gsub('j','𝐣' ) Q_bna6 = Q_bna6:gsub('k','𝐤' ) Q_bna6 = Q_bna6:gsub('l','𝐥' ) Q_bna6 = Q_bna6:gsub('m','𝐦' ) Q_bna6 = Q_bna6:gsub('n','𝐧' ) Q_bna6 = Q_bna6:gsub('o','𝐨' ) Q_bna6 = Q_bna6:gsub('p','𝐩' ) Q_bna6 = Q_bna6:gsub('q','𝐪' ) Q_bna6 = Q_bna6:gsub('r','𝐫' ) Q_bna6 = Q_bna6:gsub('s','𝐬' ) Q_bna6 = Q_bna6:gsub('t','𝐭' ) Q_bna6 = Q_bna6:gsub('u','𝐮' ) Q_bna6 = Q_bna6:gsub('v','𝐯' ) Q_bna6 = Q_bna6:gsub('w','𝐰' ) Q_bna6 = Q_bna6:gsub('x','𝐱' ) Q_bna6 = Q_bna6:gsub('y','𝐲' ) Q_bna6 = Q_bna6:gsub('z','𝐳')
local Q_bna7 = text:gsub('a','𝑎' ) Q_bna7 = Q_bna7:gsub('b','𝑏' ) Q_bna7 = Q_bna7:gsub('c','𝑐' ) Q_bna7 = Q_bna7:gsub('d','𝑑' ) Q_bna7 = Q_bna7:gsub('e','𝑒' ) Q_bna7 = Q_bna7:gsub('f','𝒇' ) Q_bna7 = Q_bna7:gsub('g','𝑔' ) Q_bna7 = Q_bna7:gsub('h','ℎ' ) Q_bna7 = Q_bna7:gsub('i','𝑖' ) Q_bna7 = Q_bna7:gsub('j','𝑗' ) Q_bna7 = Q_bna7:gsub('k','𝑘' ) Q_bna7 = Q_bna7:gsub('l','𝑙' ) Q_bna7 = Q_bna7:gsub('m','𝑚' ) Q_bna7 = Q_bna7:gsub('n','𝑛' ) Q_bna7 = Q_bna7:gsub('o','𝑜' ) Q_bna7 = Q_bna7:gsub('p','𝑝' ) Q_bna7 = Q_bna7:gsub('q','𝑞' ) Q_bna7 = Q_bna7:gsub('r','𝑟' ) Q_bna7 = Q_bna7:gsub('s','𝑠' ) Q_bna7 = Q_bna7:gsub('t','𝑡' ) Q_bna7 = Q_bna7:gsub('u','𝑢' ) Q_bna7 = Q_bna7:gsub('v','𝑣' ) Q_bna7 = Q_bna7:gsub('w','𝑤' ) Q_bna7 = Q_bna7:gsub('x','𝑥' ) Q_bna7 = Q_bna7:gsub('y','𝑦' ) Q_bna7 = Q_bna7:gsub('z','𝑧')
local Q_bna8 = text:gsub('a','ᗩ' ) Q_bna8 = Q_bna8:gsub('b','β' ) Q_bna8 = Q_bna8:gsub('c','Ｃ' ) Q_bna8 = Q_bna8:gsub('d','Ɗ' ) Q_bna8 = Q_bna8:gsub('e','Ｅ' ) Q_bna8 = Q_bna8:gsub('f','Բ' ) Q_bna8 = Q_bna8:gsub('g','Ｇ' ) Q_bna8 = Q_bna8:gsub('h','ⴼ' ) Q_bna8 = Q_bna8:gsub('i','Ｉ' ) Q_bna8 = Q_bna8:gsub('j','Ј' ) Q_bna8 = Q_bna8:gsub('k','₭' ) Q_bna8 = Q_bna8:gsub('l','Ł' ) Q_bna8 = Q_bna8:gsub('m','ᗰ' ) Q_bna8 = Q_bna8:gsub('n','Ŋ' ) Q_bna8 = Q_bna8:gsub('o','σ' ) Q_bna8 = Q_bna8:gsub('p','Ꝑ' ) Q_bna8 = Q_bna8:gsub('q','℺' ) Q_bna8 = Q_bna8:gsub('r','Ꮢ' ) Q_bna8 = Q_bna8:gsub('s','₷' ) Q_bna8 = Q_bna8:gsub('t','Ƭ' ) Q_bna8 = Q_bna8:gsub('u','ᵿ' ) Q_bna8 = Q_bna8:gsub('v','ѵ' ) Q_bna8 = Q_bna8:gsub('w','Ꮤ' ) Q_bna8 = Q_bna8:gsub('x','χ' ) Q_bna8 = Q_bna8:gsub('y','ɣ' ) Q_bna8 = Q_bna8:gsub('z','Ꙃ')
local Q_bna9 = text:gsub('a','𝒂' ) Q_bna9 = Q_bna9:gsub('b','𝒃' ) Q_bna9 = Q_bna9:gsub('c','𝒄' ) Q_bna9 = Q_bna9:gsub('d','𝒅' ) Q_bna9 = Q_bna9:gsub('e','𝒆' ) Q_bna9 = Q_bna9:gsub('f','𝒇' ) Q_bna9 = Q_bna9:gsub('g','𝒈' ) Q_bna9 = Q_bna9:gsub('h','𝒉' ) Q_bna9 = Q_bna9:gsub('i','𝒊' ) Q_bna9 = Q_bna9:gsub('j','𝒋' ) Q_bna9 = Q_bna9:gsub('k','𝒌' ) Q_bna9 = Q_bna9:gsub('l','𝒍' ) Q_bna9 = Q_bna9:gsub('m','𝒎' ) Q_bna9 = Q_bna9:gsub('n','𝒏' ) Q_bna9 = Q_bna9:gsub('o','𝒐' ) Q_bna9 = Q_bna9:gsub('p','𝒑' ) Q_bna9 = Q_bna9:gsub('q','𝒒' ) Q_bna9 = Q_bna9:gsub('r','𝒓' ) Q_bna9 = Q_bna9:gsub('s','𝒔' ) Q_bna9 = Q_bna9:gsub('t','𝒕' ) Q_bna9 = Q_bna9:gsub('u','𝒖' ) Q_bna9 = Q_bna9:gsub('v','𝒗' ) Q_bna9 = Q_bna9:gsub('w','𝒘' ) Q_bna9 = Q_bna9:gsub('x','𝒙' ) Q_bna9 = Q_bna9:gsub('y','𝒚' ) Q_bna9 = Q_bna9:gsub('z','𝒛')
local Q_bna10 = text:gsub('a','𝔸' ) Q_bna10 = Q_bna10:gsub('b','𝔹' ) Q_bna10 = Q_bna10:gsub('c','ℂ' ) Q_bna10 = Q_bna10:gsub('d','𝔻' ) Q_bna10 = Q_bna10:gsub('e','𝔼' ) Q_bna10 = Q_bna10:gsub('f','𝔽' ) Q_bna10 = Q_bna10:gsub('g','𝔾' ) Q_bna10 = Q_bna10:gsub('h','ℍ' ) Q_bna10 = Q_bna10:gsub('i','𝕀' ) Q_bna10 = Q_bna10:gsub('j','𝕁' ) Q_bna10 = Q_bna10:gsub('k','𝕂' ) Q_bna10 = Q_bna10:gsub('l','𝕃' ) Q_bna10 = Q_bna10:gsub('m','𝕄' ) Q_bna10 = Q_bna10:gsub('n','ℕ' ) Q_bna10 = Q_bna10:gsub('o','𝕆' ) Q_bna10 = Q_bna10:gsub('p','ℙ' ) Q_bna10 = Q_bna10:gsub('q','ℚ' ) Q_bna10 = Q_bna10:gsub('r','ℝ' ) Q_bna10 = Q_bna10:gsub('s','𝕊' ) Q_bna10 = Q_bna10:gsub('t','𝕋' ) Q_bna10 = Q_bna10:gsub('u','𝕌' ) Q_bna10 = Q_bna10:gsub('v','𝕍' ) Q_bna10 = Q_bna10:gsub('w','𝕎' ) Q_bna10 = Q_bna10:gsub('x','𝕏' ) Q_bna10 = Q_bna10:gsub('y','𝕐' ) Q_bna10 = Q_bna10:gsub('z','ℤ')
local Q_bna11 = text:gsub('a','𝕬 ' ) Q_bna11 = Q_bna11:gsub('b','𝕭' ) Q_bna11 = Q_bna11:gsub('c','𝕮' ) Q_bna11 = Q_bna11:gsub('d','𝕯' ) Q_bna11 = Q_bna11:gsub('e','𝕰' ) Q_bna11 = Q_bna11:gsub('f','f' ) Q_bna11 = Q_bna11:gsub('g','𝕲' ) Q_bna11 = Q_bna11:gsub('h','𝕳' ) Q_bna11 = Q_bna11:gsub('i','𝕴' ) Q_bna11 = Q_bna11:gsub('j','𝕵' ) Q_bna11 = Q_bna11:gsub('k','𝕶' ) Q_bna11 = Q_bna11:gsub('l','𝕷' ) Q_bna11 = Q_bna11:gsub('m','𝕸' ) Q_bna11 = Q_bna11:gsub('n','𝕹' ) Q_bna11 = Q_bna11:gsub('o','𝕺' ) Q_bna11 = Q_bna11:gsub('p','𝕻' ) Q_bna11 = Q_bna11:gsub('q','𝕼' ) Q_bna11 = Q_bna11:gsub('r','𝕽' ) Q_bna11 = Q_bna11:gsub('s','𝕾' ) Q_bna11 = Q_bna11:gsub('t','𝕿' ) Q_bna11 = Q_bna11:gsub('u','𝖀' ) Q_bna11 = Q_bna11:gsub('v','𝖁' ) Q_bna11 = Q_bna11:gsub('w','𝖂' ) Q_bna11 = Q_bna11:gsub('x','𝖃' ) Q_bna11 = Q_bna11:gsub('y','𝖄' ) Q_bna11 = Q_bna11:gsub('z','𝖅')
local Q_bna12 = text:gsub('a','𝐴' ) Q_bna12 = Q_bna12:gsub('b','b' ) Q_bna12 = Q_bna12:gsub('c','𝐶' ) Q_bna12 = Q_bna12:gsub('d','𝐷' ) Q_bna12 = Q_bna12:gsub('e','𝐸' ) Q_bna12 = Q_bna12:gsub('f','𝐹' ) Q_bna12 = Q_bna12:gsub('g','𝐺' ) Q_bna12 = Q_bna12:gsub('h','𝐻' ) Q_bna12 = Q_bna12:gsub('i','𝐼' ) Q_bna12 = Q_bna12:gsub('j','𝐽' ) Q_bna12 = Q_bna12:gsub('k','𝐾' ) Q_bna12 = Q_bna12:gsub('l','𝐿' ) Q_bna12 = Q_bna12:gsub('m','𝑀' ) Q_bna12 = Q_bna12:gsub('n','𝑁' ) Q_bna12 = Q_bna12:gsub('o','𝑂' ) Q_bna12 = Q_bna12:gsub('p','𝑃' ) Q_bna12 = Q_bna12:gsub('q','𝑄' ) Q_bna12 = Q_bna12:gsub('r','𝑅' ) Q_bna12 = Q_bna12:gsub('s','𝑆' ) Q_bna12 = Q_bna12:gsub('t','𝑇' ) Q_bna12 = Q_bna12:gsub('u','𝐔' ) Q_bna12 = Q_bna12:gsub('v','𝑉' ) Q_bna12 = Q_bna12:gsub('w','𝑊' ) Q_bna12 = Q_bna12:gsub('x','𝑋' ) Q_bna12 = Q_bna12:gsub('y','𝑌' ) Q_bna12 = Q_bna12:gsub('z','𝑍')
local Q_bna13 = text:gsub('a','𝓪 ' ) Q_bna13 = Q_bna13:gsub('b','𝓫' ) Q_bna13 = Q_bna13:gsub('c','𝓬' ) Q_bna13 = Q_bna13:gsub('d','??' ) Q_bna13 = Q_bna13:gsub('e','𝓮' ) Q_bna13 = Q_bna13:gsub('f','𝓯' ) Q_bna13 = Q_bna13:gsub('g','𝓰' ) Q_bna13 = Q_bna13:gsub('h','𝓱' ) Q_bna13 = Q_bna13:gsub('i','𝓲' ) Q_bna13 = Q_bna13:gsub('j','𝓳' ) Q_bna13 = Q_bna13:gsub('k','𝓴' ) Q_bna13 = Q_bna13:gsub('l','𝓵' ) Q_bna13 = Q_bna13:gsub('m','𝓶' ) Q_bna13 = Q_bna13:gsub('n','𝓷' ) Q_bna13 = Q_bna13:gsub('o','𝓸' ) Q_bna13 = Q_bna13:gsub('p','𝓹' ) Q_bna13 = Q_bna13:gsub('q','𝓺' ) Q_bna13 = Q_bna13:gsub('r','𝓻' ) Q_bna13 = Q_bna13:gsub('s','𝓼' ) Q_bna13 = Q_bna13:gsub('t','𝓽' ) Q_bna13 = Q_bna13:gsub('u','𝓾' ) Q_bna13 = Q_bna13:gsub('v','𝓾' ) Q_bna13 = Q_bna13:gsub('w','𝔀' ) Q_bna13 = Q_bna13:gsub('x','𝔁' ) Q_bna13 = Q_bna13:gsub('y','𝔂' ) Q_bna13 = Q_bna13:gsub('z','𝔃')
local Q_bna14 = text:gsub('a','𝙰' ) Q_bna14 = Q_bna14:gsub('b','𝙱' ) Q_bna14 = Q_bna14:gsub('c','𝙲' ) Q_bna14 = Q_bna14:gsub('d','𝙳' ) Q_bna14 = Q_bna14:gsub('e','𝙴' ) Q_bna14 = Q_bna14:gsub('f','𝙵' ) Q_bna14 = Q_bna14:gsub('g','𝙶' ) Q_bna14 = Q_bna14:gsub('h','𝙷' ) Q_bna14 = Q_bna14:gsub('i','𝙸' ) Q_bna14 = Q_bna14:gsub('j','𝙹' ) Q_bna14 = Q_bna14:gsub('k','𝙺' ) Q_bna14 = Q_bna14:gsub('l','𝙻' ) Q_bna14 = Q_bna14:gsub('m','𝙼' ) Q_bna14 = Q_bna14:gsub('n','𝙽' ) Q_bna14 = Q_bna14:gsub('o','𝙾' ) Q_bna14 = Q_bna14:gsub('p','𝙿' ) Q_bna14 = Q_bna14:gsub('q','𝚀' ) Q_bna14 = Q_bna14:gsub('r','𝚁' ) Q_bna14 = Q_bna14:gsub('s','𝚂' ) Q_bna14 = Q_bna14:gsub('t','𝚃' ) Q_bna14 = Q_bna14:gsub('u','𝙺' ) Q_bna14 = Q_bna14:gsub('v','𝚅' ) Q_bna14 = Q_bna14:gsub('w','𝚆' ) Q_bna14 = Q_bna14:gsub('x','𝚇' ) Q_bna14 = Q_bna14:gsub('y','𝚈' ) Q_bna14 = Q_bna14:gsub('z','𝚉')
local Q_bna15 = text:gsub('a','𝖆' ) Q_bna15 = Q_bna15:gsub('b','𝖇' ) Q_bna15 = Q_bna15:gsub('c','𝖈' ) Q_bna15 = Q_bna15:gsub('d','??' ) Q_bna15 = Q_bna15:gsub('e','𝖊' ) Q_bna15 = Q_bna15:gsub('f','𝖋' ) Q_bna15 = Q_bna15:gsub('g','𝖌' ) Q_bna15 = Q_bna15:gsub('h','𝖍' ) Q_bna15 = Q_bna15:gsub('i','𝖎' ) Q_bna15 = Q_bna15:gsub('j','𝖏' ) Q_bna15 = Q_bna15:gsub('k','𝖐' ) Q_bna15 = Q_bna15:gsub('l','𝖑' ) Q_bna15 = Q_bna15:gsub('m','𝖒' ) Q_bna15 = Q_bna15:gsub('n','𝖓' ) Q_bna15 = Q_bna15:gsub('o','𝖔' ) Q_bna15 = Q_bna15:gsub('p','𝖕' ) Q_bna15 = Q_bna15:gsub('q','𝖖' ) Q_bna15 = Q_bna15:gsub('r','𝖗' ) Q_bna15 = Q_bna15:gsub('s','𝖘' ) Q_bna15 = Q_bna15:gsub('t','𝖙' ) Q_bna15 = Q_bna15:gsub('u','𝖚' ) Q_bna15 = Q_bna15:gsub('v','𝖛' ) Q_bna15 = Q_bna15:gsub('w','𝖜' ) Q_bna15 = Q_bna15:gsub('x','𝖝' ) Q_bna15 = Q_bna15:gsub('y','𝖞' ) Q_bna15 = Q_bna15:gsub('z','𝖟')
local Q_bna16 = text:gsub('a','🅰' ) Q_bna16 = Q_bna16:gsub('b','🅱' ) Q_bna16 = Q_bna16:gsub('c','🅲' ) Q_bna16 = Q_bna16:gsub('d','🅳' ) Q_bna16 = Q_bna16:gsub('e','🅴' ) Q_bna16 = Q_bna16:gsub('f','🅵' ) Q_bna16 = Q_bna16:gsub('g','🅶' ) Q_bna16 = Q_bna16:gsub('h','🅷' ) Q_bna16 = Q_bna16:gsub('i','🅸' ) Q_bna16 = Q_bna16:gsub('j','🅹' ) Q_bna16 = Q_bna16:gsub('k','🅺' ) Q_bna16 = Q_bna16:gsub('l','🅻' ) Q_bna16 = Q_bna16:gsub('m','🅼' ) Q_bna16 = Q_bna16:gsub('n','🅽' ) Q_bna16 = Q_bna16:gsub('o','🅾' ) Q_bna16 = Q_bna16:gsub('p','🅿' ) Q_bna16 = Q_bna16:gsub('q','🆀' ) Q_bna16 = Q_bna16:gsub('r','🆁' ) Q_bna16 = Q_bna16:gsub('s','🆂' ) Q_bna16 = Q_bna16:gsub('t','🆃' ) Q_bna16 = Q_bna16:gsub('u','🆄' ) Q_bna16 = Q_bna16:gsub('v','🆅' ) Q_bna16 = Q_bna16:gsub('w','🆆' ) Q_bna16 = Q_bna16:gsub('x','🆇' ) Q_bna16 = Q_bna16:gsub('y','🆈' ) Q_bna16 = Q_bna16:gsub('z','🆉')                
local Q_bna17 = text:gsub('a','🄰' ) Q_bna17 = Q_bna17:gsub('b','🄱' ) Q_bna17 = Q_bna17:gsub('c','🄲' ) Q_bna17 = Q_bna17:gsub('d','🄳' ) Q_bna17 = Q_bna17:gsub('e','🄴' ) Q_bna17 = Q_bna17:gsub('f','🄵' ) Q_bna17 = Q_bna17:gsub('g','🄶' ) Q_bna17 = Q_bna17:gsub('h','🄷' ) Q_bna17 = Q_bna17:gsub('i','🄸' ) Q_bna17 = Q_bna17:gsub('j','🄹' ) Q_bna17 = Q_bna17:gsub('k','🄺' ) Q_bna17 = Q_bna17:gsub('l','🄻' ) Q_bna17 = Q_bna17:gsub('m','🄼' ) Q_bna17 = Q_bna17:gsub('n','🄽' ) Q_bna17 = Q_bna17:gsub('o','🄾' ) Q_bna17 = Q_bna17:gsub('p','🄿' ) Q_bna17 = Q_bna17:gsub('q','🅀' ) Q_bna17 = Q_bna17:gsub('r','🅁' ) Q_bna17 = Q_bna17:gsub('s','🅂' ) Q_bna17 = Q_bna17:gsub('t','🅃' ) Q_bna17 = Q_bna17:gsub('u','🅄' ) Q_bna17 = Q_bna17:gsub('v','🅅' ) Q_bna17 = Q_bna17:gsub('w','🅆' ) Q_bna17 = Q_bna17:gsub('x','🅇' ) Q_bna17 = Q_bna17:gsub('y','🅈' ) Q_bna17 = Q_bna17:gsub('z','🅉')
local Q_bna18 = text:gsub('a','🅐' ) Q_bna18= Q_bna18:gsub('b','🅑' ) Q_bna18= Q_bna18:gsub('c','🅒' ) Q_bna18= Q_bna18:gsub('d','🅓') Q_bna18 = Q_bna18:gsub('e','🅔' ) Q_bna18= Q_bna18:gsub('f','🅕' ) Q_bna18= Q_bna18:gsub('g','🅖' ) Q_bna18= Q_bna18:gsub('h','🅗' ) Q_bna18= Q_bna18:gsub('i','🅘' ) Q_bna18= Q_bna18:gsub('j','🅙' ) Q_bna18= Q_bna18:gsub('k','🅚' ) Q_bna18= Q_bna18:gsub('l','🅛' ) Q_bna18= Q_bna18:gsub('m','🅜' ) Q_bna18= Q_bna18:gsub('n','🅝' ) Q_bna18= Q_bna18:gsub('o','🅞' ) Q_bna18= Q_bna18:gsub('p','🅟' ) Q_bna18= Q_bna18:gsub('q','🅠' ) Q_bna18= Q_bna18:gsub('r','🅡' ) Q_bna18= Q_bna18:gsub('s','🅢' ) Q_bna18= Q_bna18:gsub('t','🅣' ) Q_bna18= Q_bna18:gsub('u','🅤' ) Q_bna18= Q_bna18:gsub('v','🅥' ) Q_bna18= Q_bna18:gsub('w','🅦' ) Q_bna18= Q_bna18:gsub('x','🅧' ) Q_bna18= Q_bna18:gsub('y','🅨' ) Q_bna18= Q_bna18:gsub('z','🅩')
Text_Zhrfa = '1 - `'..Q_bna1..'`'..'\n2 - `'..Q_bna2..'`'..
'\n3 - `'..Q_bna3..'`'..
'\n4 - `'..Q_bna4..'`'..
'\n5 - `'..Q_bna5..'`'..
'\n6 - `'..Q_bna6..'`'..
'\n7 - `'..Q_bna7..'`'..
'\n8 - `'..Q_bna8..'`'..
'\n9 - `'..Q_bna9..'`'..
'\n10 - `'..Q_bna10..'`'..
'\n11 - `'..Q_bna11..'`'..
'\n12 - `'..Q_bna12..'`'..
'\n13 - `'..Q_bna13..'`'..
'\n14 -  `'..Q_bna14..'`'..
'\n15 -  `'..Q_bna15..'`'..
'\n16 -  `'..Q_bna16..'`'..
'\n17 -  `'..Q_bna17..'`'..
'\n18 - `'..Q_bna18..'`'
Text_Zhrfa = Text_Zhrfa.."\n•  اضغط ع الاسم ليتم النسخ \n✓"
return bot.sendText(msg_chat_id,msg_id,Text_Zhrfa,"md",true)  
end

end
return {Fast = zhrfa}